// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flwr/proto/clientappio.proto

#include "flwr/proto/clientappio.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace flwr {
namespace proto {
}  // namespace proto
}  // namespace flwr
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_flwr_2fproto_2fclientappio_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_flwr_2fproto_2fclientappio_2eproto = nullptr;
const uint32_t TableStruct_flwr_2fproto_2fclientappio_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_flwr_2fproto_2fclientappio_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\034flwr/proto/clientappio.proto\022\nflwr.pro"
  "to\032\032flwr/proto/heartbeat.proto\032\024flwr/pro"
  "to/run.proto\032\030flwr/proto/message.proto\032\026"
  "flwr/proto/appio.proto2\353\007\n\013ClientAppIo\022_"
  "\n\020ListAppsToLaunch\022#.flwr.proto.ListApps"
  "ToLaunchRequest\032$.flwr.proto.ListAppsToL"
  "aunchResponse\"\000\022S\n\014RequestToken\022\037.flwr.p"
  "roto.RequestTokenRequest\032 .flwr.proto.Re"
  "questTokenResponse\"\000\022A\n\006GetRun\022\031.flwr.pr"
  "oto.GetRunRequest\032\032.flwr.proto.GetRunRes"
  "ponse\"\000\022\\\n\023PullClientAppInputs\022 .flwr.pr"
  "oto.PullAppInputsRequest\032!.flwr.proto.Pu"
  "llAppInputsResponse\"\000\022_\n\024PushClientAppOu"
  "tputs\022!.flwr.proto.PushAppOutputsRequest"
  "\032\".flwr.proto.PushAppOutputsResponse\"\000\022X"
  "\n\013PushMessage\022\".flwr.proto.PushAppMessag"
  "esRequest\032#.flwr.proto.PushAppMessagesRe"
  "sponse\"\000\022X\n\013PullMessage\022\".flwr.proto.Pul"
  "lAppMessagesRequest\032#.flwr.proto.PullApp"
  "MessagesResponse\"\000\022_\n\020SendAppHeartbeat\022#"
  ".flwr.proto.SendAppHeartbeatRequest\032$.fl"
  "wr.proto.SendAppHeartbeatResponse\"\000\022M\n\nP"
  "ushObject\022\035.flwr.proto.PushObjectRequest"
  "\032\036.flwr.proto.PushObjectResponse\"\000\022M\n\nPu"
  "llObject\022\035.flwr.proto.PullObjectRequest\032"
  "\036.flwr.proto.PullObjectResponse\"\000\022q\n\026Con"
  "firmMessageReceived\022).flwr.proto.Confirm"
  "MessageReceivedRequest\032*.flwr.proto.Conf"
  "irmMessageReceivedResponse\"\000b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_flwr_2fproto_2fclientappio_2eproto_deps[4] = {
  &::descriptor_table_flwr_2fproto_2fappio_2eproto,
  &::descriptor_table_flwr_2fproto_2fheartbeat_2eproto,
  &::descriptor_table_flwr_2fproto_2fmessage_2eproto,
  &::descriptor_table_flwr_2fproto_2frun_2eproto,
};
static ::_pbi::once_flag descriptor_table_flwr_2fproto_2fclientappio_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_flwr_2fproto_2fclientappio_2eproto = {
    false, false, 1156, descriptor_table_protodef_flwr_2fproto_2fclientappio_2eproto,
    "flwr/proto/clientappio.proto",
    &descriptor_table_flwr_2fproto_2fclientappio_2eproto_once, descriptor_table_flwr_2fproto_2fclientappio_2eproto_deps, 4, 0,
    schemas, file_default_instances, TableStruct_flwr_2fproto_2fclientappio_2eproto::offsets,
    nullptr, file_level_enum_descriptors_flwr_2fproto_2fclientappio_2eproto,
    file_level_service_descriptors_flwr_2fproto_2fclientappio_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_flwr_2fproto_2fclientappio_2eproto_getter() {
  return &descriptor_table_flwr_2fproto_2fclientappio_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_flwr_2fproto_2fclientappio_2eproto(&descriptor_table_flwr_2fproto_2fclientappio_2eproto);
namespace flwr {
namespace proto {

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace flwr
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
