// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: flwr/proto/clientappio.proto

#include "flwr/proto/clientappio.pb.h"
#include "flwr/proto/clientappio.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace flwr {
namespace proto {

static const char* ClientAppIo_method_names[] = {
  "/flwr.proto.ClientAppIo/ListAppsToLaunch",
  "/flwr.proto.ClientAppIo/RequestToken",
  "/flwr.proto.ClientAppIo/GetRun",
  "/flwr.proto.ClientAppIo/PullClientAppInputs",
  "/flwr.proto.ClientAppIo/PushClientAppOutputs",
  "/flwr.proto.ClientAppIo/PushMessage",
  "/flwr.proto.ClientAppIo/PullMessage",
  "/flwr.proto.ClientAppIo/SendAppHeartbeat",
  "/flwr.proto.ClientAppIo/PushObject",
  "/flwr.proto.ClientAppIo/PullObject",
  "/flwr.proto.ClientAppIo/ConfirmMessageReceived",
};

std::unique_ptr< ClientAppIo::Stub> ClientAppIo::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ClientAppIo::Stub> stub(new ClientAppIo::Stub(channel, options));
  return stub;
}

ClientAppIo::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ListAppsToLaunch_(ClientAppIo_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RequestToken_(ClientAppIo_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRun_(ClientAppIo_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PullClientAppInputs_(ClientAppIo_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PushClientAppOutputs_(ClientAppIo_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PushMessage_(ClientAppIo_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PullMessage_(ClientAppIo_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendAppHeartbeat_(ClientAppIo_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PushObject_(ClientAppIo_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PullObject_(ClientAppIo_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ConfirmMessageReceived_(ClientAppIo_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ClientAppIo::Stub::ListAppsToLaunch(::grpc::ClientContext* context, const ::flwr::proto::ListAppsToLaunchRequest& request, ::flwr::proto::ListAppsToLaunchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::ListAppsToLaunchRequest, ::flwr::proto::ListAppsToLaunchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListAppsToLaunch_, context, request, response);
}

void ClientAppIo::Stub::async::ListAppsToLaunch(::grpc::ClientContext* context, const ::flwr::proto::ListAppsToLaunchRequest* request, ::flwr::proto::ListAppsToLaunchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::ListAppsToLaunchRequest, ::flwr::proto::ListAppsToLaunchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListAppsToLaunch_, context, request, response, std::move(f));
}

void ClientAppIo::Stub::async::ListAppsToLaunch(::grpc::ClientContext* context, const ::flwr::proto::ListAppsToLaunchRequest* request, ::flwr::proto::ListAppsToLaunchResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListAppsToLaunch_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::ListAppsToLaunchResponse>* ClientAppIo::Stub::PrepareAsyncListAppsToLaunchRaw(::grpc::ClientContext* context, const ::flwr::proto::ListAppsToLaunchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::ListAppsToLaunchResponse, ::flwr::proto::ListAppsToLaunchRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListAppsToLaunch_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::ListAppsToLaunchResponse>* ClientAppIo::Stub::AsyncListAppsToLaunchRaw(::grpc::ClientContext* context, const ::flwr::proto::ListAppsToLaunchRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListAppsToLaunchRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ClientAppIo::Stub::RequestToken(::grpc::ClientContext* context, const ::flwr::proto::RequestTokenRequest& request, ::flwr::proto::RequestTokenResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::RequestTokenRequest, ::flwr::proto::RequestTokenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RequestToken_, context, request, response);
}

void ClientAppIo::Stub::async::RequestToken(::grpc::ClientContext* context, const ::flwr::proto::RequestTokenRequest* request, ::flwr::proto::RequestTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::RequestTokenRequest, ::flwr::proto::RequestTokenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestToken_, context, request, response, std::move(f));
}

void ClientAppIo::Stub::async::RequestToken(::grpc::ClientContext* context, const ::flwr::proto::RequestTokenRequest* request, ::flwr::proto::RequestTokenResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::RequestTokenResponse>* ClientAppIo::Stub::PrepareAsyncRequestTokenRaw(::grpc::ClientContext* context, const ::flwr::proto::RequestTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::RequestTokenResponse, ::flwr::proto::RequestTokenRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RequestToken_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::RequestTokenResponse>* ClientAppIo::Stub::AsyncRequestTokenRaw(::grpc::ClientContext* context, const ::flwr::proto::RequestTokenRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestTokenRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ClientAppIo::Stub::GetRun(::grpc::ClientContext* context, const ::flwr::proto::GetRunRequest& request, ::flwr::proto::GetRunResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::GetRunRequest, ::flwr::proto::GetRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRun_, context, request, response);
}

void ClientAppIo::Stub::async::GetRun(::grpc::ClientContext* context, const ::flwr::proto::GetRunRequest* request, ::flwr::proto::GetRunResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::GetRunRequest, ::flwr::proto::GetRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRun_, context, request, response, std::move(f));
}

void ClientAppIo::Stub::async::GetRun(::grpc::ClientContext* context, const ::flwr::proto::GetRunRequest* request, ::flwr::proto::GetRunResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRun_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::GetRunResponse>* ClientAppIo::Stub::PrepareAsyncGetRunRaw(::grpc::ClientContext* context, const ::flwr::proto::GetRunRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::GetRunResponse, ::flwr::proto::GetRunRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRun_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::GetRunResponse>* ClientAppIo::Stub::AsyncGetRunRaw(::grpc::ClientContext* context, const ::flwr::proto::GetRunRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRunRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ClientAppIo::Stub::PullClientAppInputs(::grpc::ClientContext* context, const ::flwr::proto::PullAppInputsRequest& request, ::flwr::proto::PullAppInputsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::PullAppInputsRequest, ::flwr::proto::PullAppInputsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PullClientAppInputs_, context, request, response);
}

void ClientAppIo::Stub::async::PullClientAppInputs(::grpc::ClientContext* context, const ::flwr::proto::PullAppInputsRequest* request, ::flwr::proto::PullAppInputsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::PullAppInputsRequest, ::flwr::proto::PullAppInputsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PullClientAppInputs_, context, request, response, std::move(f));
}

void ClientAppIo::Stub::async::PullClientAppInputs(::grpc::ClientContext* context, const ::flwr::proto::PullAppInputsRequest* request, ::flwr::proto::PullAppInputsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PullClientAppInputs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PullAppInputsResponse>* ClientAppIo::Stub::PrepareAsyncPullClientAppInputsRaw(::grpc::ClientContext* context, const ::flwr::proto::PullAppInputsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::PullAppInputsResponse, ::flwr::proto::PullAppInputsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PullClientAppInputs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PullAppInputsResponse>* ClientAppIo::Stub::AsyncPullClientAppInputsRaw(::grpc::ClientContext* context, const ::flwr::proto::PullAppInputsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPullClientAppInputsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ClientAppIo::Stub::PushClientAppOutputs(::grpc::ClientContext* context, const ::flwr::proto::PushAppOutputsRequest& request, ::flwr::proto::PushAppOutputsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::PushAppOutputsRequest, ::flwr::proto::PushAppOutputsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushClientAppOutputs_, context, request, response);
}

void ClientAppIo::Stub::async::PushClientAppOutputs(::grpc::ClientContext* context, const ::flwr::proto::PushAppOutputsRequest* request, ::flwr::proto::PushAppOutputsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::PushAppOutputsRequest, ::flwr::proto::PushAppOutputsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushClientAppOutputs_, context, request, response, std::move(f));
}

void ClientAppIo::Stub::async::PushClientAppOutputs(::grpc::ClientContext* context, const ::flwr::proto::PushAppOutputsRequest* request, ::flwr::proto::PushAppOutputsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushClientAppOutputs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PushAppOutputsResponse>* ClientAppIo::Stub::PrepareAsyncPushClientAppOutputsRaw(::grpc::ClientContext* context, const ::flwr::proto::PushAppOutputsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::PushAppOutputsResponse, ::flwr::proto::PushAppOutputsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushClientAppOutputs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PushAppOutputsResponse>* ClientAppIo::Stub::AsyncPushClientAppOutputsRaw(::grpc::ClientContext* context, const ::flwr::proto::PushAppOutputsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushClientAppOutputsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ClientAppIo::Stub::PushMessage(::grpc::ClientContext* context, const ::flwr::proto::PushAppMessagesRequest& request, ::flwr::proto::PushAppMessagesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::PushAppMessagesRequest, ::flwr::proto::PushAppMessagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushMessage_, context, request, response);
}

void ClientAppIo::Stub::async::PushMessage(::grpc::ClientContext* context, const ::flwr::proto::PushAppMessagesRequest* request, ::flwr::proto::PushAppMessagesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::PushAppMessagesRequest, ::flwr::proto::PushAppMessagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushMessage_, context, request, response, std::move(f));
}

void ClientAppIo::Stub::async::PushMessage(::grpc::ClientContext* context, const ::flwr::proto::PushAppMessagesRequest* request, ::flwr::proto::PushAppMessagesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PushAppMessagesResponse>* ClientAppIo::Stub::PrepareAsyncPushMessageRaw(::grpc::ClientContext* context, const ::flwr::proto::PushAppMessagesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::PushAppMessagesResponse, ::flwr::proto::PushAppMessagesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PushAppMessagesResponse>* ClientAppIo::Stub::AsyncPushMessageRaw(::grpc::ClientContext* context, const ::flwr::proto::PushAppMessagesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ClientAppIo::Stub::PullMessage(::grpc::ClientContext* context, const ::flwr::proto::PullAppMessagesRequest& request, ::flwr::proto::PullAppMessagesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::PullAppMessagesRequest, ::flwr::proto::PullAppMessagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PullMessage_, context, request, response);
}

void ClientAppIo::Stub::async::PullMessage(::grpc::ClientContext* context, const ::flwr::proto::PullAppMessagesRequest* request, ::flwr::proto::PullAppMessagesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::PullAppMessagesRequest, ::flwr::proto::PullAppMessagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PullMessage_, context, request, response, std::move(f));
}

void ClientAppIo::Stub::async::PullMessage(::grpc::ClientContext* context, const ::flwr::proto::PullAppMessagesRequest* request, ::flwr::proto::PullAppMessagesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PullMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PullAppMessagesResponse>* ClientAppIo::Stub::PrepareAsyncPullMessageRaw(::grpc::ClientContext* context, const ::flwr::proto::PullAppMessagesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::PullAppMessagesResponse, ::flwr::proto::PullAppMessagesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PullMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PullAppMessagesResponse>* ClientAppIo::Stub::AsyncPullMessageRaw(::grpc::ClientContext* context, const ::flwr::proto::PullAppMessagesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPullMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ClientAppIo::Stub::SendAppHeartbeat(::grpc::ClientContext* context, const ::flwr::proto::SendAppHeartbeatRequest& request, ::flwr::proto::SendAppHeartbeatResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::SendAppHeartbeatRequest, ::flwr::proto::SendAppHeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendAppHeartbeat_, context, request, response);
}

void ClientAppIo::Stub::async::SendAppHeartbeat(::grpc::ClientContext* context, const ::flwr::proto::SendAppHeartbeatRequest* request, ::flwr::proto::SendAppHeartbeatResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::SendAppHeartbeatRequest, ::flwr::proto::SendAppHeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendAppHeartbeat_, context, request, response, std::move(f));
}

void ClientAppIo::Stub::async::SendAppHeartbeat(::grpc::ClientContext* context, const ::flwr::proto::SendAppHeartbeatRequest* request, ::flwr::proto::SendAppHeartbeatResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendAppHeartbeat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::SendAppHeartbeatResponse>* ClientAppIo::Stub::PrepareAsyncSendAppHeartbeatRaw(::grpc::ClientContext* context, const ::flwr::proto::SendAppHeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::SendAppHeartbeatResponse, ::flwr::proto::SendAppHeartbeatRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendAppHeartbeat_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::SendAppHeartbeatResponse>* ClientAppIo::Stub::AsyncSendAppHeartbeatRaw(::grpc::ClientContext* context, const ::flwr::proto::SendAppHeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendAppHeartbeatRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ClientAppIo::Stub::PushObject(::grpc::ClientContext* context, const ::flwr::proto::PushObjectRequest& request, ::flwr::proto::PushObjectResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::PushObjectRequest, ::flwr::proto::PushObjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushObject_, context, request, response);
}

void ClientAppIo::Stub::async::PushObject(::grpc::ClientContext* context, const ::flwr::proto::PushObjectRequest* request, ::flwr::proto::PushObjectResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::PushObjectRequest, ::flwr::proto::PushObjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushObject_, context, request, response, std::move(f));
}

void ClientAppIo::Stub::async::PushObject(::grpc::ClientContext* context, const ::flwr::proto::PushObjectRequest* request, ::flwr::proto::PushObjectResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushObject_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PushObjectResponse>* ClientAppIo::Stub::PrepareAsyncPushObjectRaw(::grpc::ClientContext* context, const ::flwr::proto::PushObjectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::PushObjectResponse, ::flwr::proto::PushObjectRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushObject_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PushObjectResponse>* ClientAppIo::Stub::AsyncPushObjectRaw(::grpc::ClientContext* context, const ::flwr::proto::PushObjectRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushObjectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ClientAppIo::Stub::PullObject(::grpc::ClientContext* context, const ::flwr::proto::PullObjectRequest& request, ::flwr::proto::PullObjectResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::PullObjectRequest, ::flwr::proto::PullObjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PullObject_, context, request, response);
}

void ClientAppIo::Stub::async::PullObject(::grpc::ClientContext* context, const ::flwr::proto::PullObjectRequest* request, ::flwr::proto::PullObjectResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::PullObjectRequest, ::flwr::proto::PullObjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PullObject_, context, request, response, std::move(f));
}

void ClientAppIo::Stub::async::PullObject(::grpc::ClientContext* context, const ::flwr::proto::PullObjectRequest* request, ::flwr::proto::PullObjectResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PullObject_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PullObjectResponse>* ClientAppIo::Stub::PrepareAsyncPullObjectRaw(::grpc::ClientContext* context, const ::flwr::proto::PullObjectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::PullObjectResponse, ::flwr::proto::PullObjectRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PullObject_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PullObjectResponse>* ClientAppIo::Stub::AsyncPullObjectRaw(::grpc::ClientContext* context, const ::flwr::proto::PullObjectRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPullObjectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ClientAppIo::Stub::ConfirmMessageReceived(::grpc::ClientContext* context, const ::flwr::proto::ConfirmMessageReceivedRequest& request, ::flwr::proto::ConfirmMessageReceivedResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::ConfirmMessageReceivedRequest, ::flwr::proto::ConfirmMessageReceivedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ConfirmMessageReceived_, context, request, response);
}

void ClientAppIo::Stub::async::ConfirmMessageReceived(::grpc::ClientContext* context, const ::flwr::proto::ConfirmMessageReceivedRequest* request, ::flwr::proto::ConfirmMessageReceivedResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::ConfirmMessageReceivedRequest, ::flwr::proto::ConfirmMessageReceivedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConfirmMessageReceived_, context, request, response, std::move(f));
}

void ClientAppIo::Stub::async::ConfirmMessageReceived(::grpc::ClientContext* context, const ::flwr::proto::ConfirmMessageReceivedRequest* request, ::flwr::proto::ConfirmMessageReceivedResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConfirmMessageReceived_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::ConfirmMessageReceivedResponse>* ClientAppIo::Stub::PrepareAsyncConfirmMessageReceivedRaw(::grpc::ClientContext* context, const ::flwr::proto::ConfirmMessageReceivedRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::ConfirmMessageReceivedResponse, ::flwr::proto::ConfirmMessageReceivedRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ConfirmMessageReceived_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::ConfirmMessageReceivedResponse>* ClientAppIo::Stub::AsyncConfirmMessageReceivedRaw(::grpc::ClientContext* context, const ::flwr::proto::ConfirmMessageReceivedRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConfirmMessageReceivedRaw(context, request, cq);
  result->StartCall();
  return result;
}

ClientAppIo::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientAppIo_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientAppIo::Service, ::flwr::proto::ListAppsToLaunchRequest, ::flwr::proto::ListAppsToLaunchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::ListAppsToLaunchRequest* req,
             ::flwr::proto::ListAppsToLaunchResponse* resp) {
               return service->ListAppsToLaunch(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientAppIo_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientAppIo::Service, ::flwr::proto::RequestTokenRequest, ::flwr::proto::RequestTokenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::RequestTokenRequest* req,
             ::flwr::proto::RequestTokenResponse* resp) {
               return service->RequestToken(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientAppIo_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientAppIo::Service, ::flwr::proto::GetRunRequest, ::flwr::proto::GetRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::GetRunRequest* req,
             ::flwr::proto::GetRunResponse* resp) {
               return service->GetRun(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientAppIo_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientAppIo::Service, ::flwr::proto::PullAppInputsRequest, ::flwr::proto::PullAppInputsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::PullAppInputsRequest* req,
             ::flwr::proto::PullAppInputsResponse* resp) {
               return service->PullClientAppInputs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientAppIo_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientAppIo::Service, ::flwr::proto::PushAppOutputsRequest, ::flwr::proto::PushAppOutputsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::PushAppOutputsRequest* req,
             ::flwr::proto::PushAppOutputsResponse* resp) {
               return service->PushClientAppOutputs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientAppIo_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientAppIo::Service, ::flwr::proto::PushAppMessagesRequest, ::flwr::proto::PushAppMessagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::PushAppMessagesRequest* req,
             ::flwr::proto::PushAppMessagesResponse* resp) {
               return service->PushMessage(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientAppIo_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientAppIo::Service, ::flwr::proto::PullAppMessagesRequest, ::flwr::proto::PullAppMessagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::PullAppMessagesRequest* req,
             ::flwr::proto::PullAppMessagesResponse* resp) {
               return service->PullMessage(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientAppIo_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientAppIo::Service, ::flwr::proto::SendAppHeartbeatRequest, ::flwr::proto::SendAppHeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::SendAppHeartbeatRequest* req,
             ::flwr::proto::SendAppHeartbeatResponse* resp) {
               return service->SendAppHeartbeat(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientAppIo_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientAppIo::Service, ::flwr::proto::PushObjectRequest, ::flwr::proto::PushObjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::PushObjectRequest* req,
             ::flwr::proto::PushObjectResponse* resp) {
               return service->PushObject(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientAppIo_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientAppIo::Service, ::flwr::proto::PullObjectRequest, ::flwr::proto::PullObjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::PullObjectRequest* req,
             ::flwr::proto::PullObjectResponse* resp) {
               return service->PullObject(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientAppIo_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientAppIo::Service, ::flwr::proto::ConfirmMessageReceivedRequest, ::flwr::proto::ConfirmMessageReceivedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::ConfirmMessageReceivedRequest* req,
             ::flwr::proto::ConfirmMessageReceivedResponse* resp) {
               return service->ConfirmMessageReceived(ctx, req, resp);
             }, this)));
}

ClientAppIo::Service::~Service() {
}

::grpc::Status ClientAppIo::Service::ListAppsToLaunch(::grpc::ServerContext* context, const ::flwr::proto::ListAppsToLaunchRequest* request, ::flwr::proto::ListAppsToLaunchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ClientAppIo::Service::RequestToken(::grpc::ServerContext* context, const ::flwr::proto::RequestTokenRequest* request, ::flwr::proto::RequestTokenResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ClientAppIo::Service::GetRun(::grpc::ServerContext* context, const ::flwr::proto::GetRunRequest* request, ::flwr::proto::GetRunResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ClientAppIo::Service::PullClientAppInputs(::grpc::ServerContext* context, const ::flwr::proto::PullAppInputsRequest* request, ::flwr::proto::PullAppInputsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ClientAppIo::Service::PushClientAppOutputs(::grpc::ServerContext* context, const ::flwr::proto::PushAppOutputsRequest* request, ::flwr::proto::PushAppOutputsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ClientAppIo::Service::PushMessage(::grpc::ServerContext* context, const ::flwr::proto::PushAppMessagesRequest* request, ::flwr::proto::PushAppMessagesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ClientAppIo::Service::PullMessage(::grpc::ServerContext* context, const ::flwr::proto::PullAppMessagesRequest* request, ::flwr::proto::PullAppMessagesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ClientAppIo::Service::SendAppHeartbeat(::grpc::ServerContext* context, const ::flwr::proto::SendAppHeartbeatRequest* request, ::flwr::proto::SendAppHeartbeatResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ClientAppIo::Service::PushObject(::grpc::ServerContext* context, const ::flwr::proto::PushObjectRequest* request, ::flwr::proto::PushObjectResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ClientAppIo::Service::PullObject(::grpc::ServerContext* context, const ::flwr::proto::PullObjectRequest* request, ::flwr::proto::PullObjectResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ClientAppIo::Service::ConfirmMessageReceived(::grpc::ServerContext* context, const ::flwr::proto::ConfirmMessageReceivedRequest* request, ::flwr::proto::ConfirmMessageReceivedResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace flwr
}  // namespace proto

