// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: flwr/proto/control.proto

#include "flwr/proto/control.pb.h"
#include "flwr/proto/control.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace flwr {
namespace proto {

static const char* Control_method_names[] = {
  "/flwr.proto.Control/StartRun",
  "/flwr.proto.Control/StopRun",
  "/flwr.proto.Control/StreamLogs",
  "/flwr.proto.Control/ListRuns",
  "/flwr.proto.Control/GetLoginDetails",
  "/flwr.proto.Control/GetAuthTokens",
  "/flwr.proto.Control/PullArtifacts",
  "/flwr.proto.Control/RegisterNode",
  "/flwr.proto.Control/UnregisterNode",
  "/flwr.proto.Control/ListNodes",
  "/flwr.proto.Control/ListFederations",
  "/flwr.proto.Control/ShowFederation",
};

std::unique_ptr< Control::Stub> Control::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Control::Stub> stub(new Control::Stub(channel, options));
  return stub;
}

Control::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StartRun_(Control_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopRun_(Control_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamLogs_(Control_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ListRuns_(Control_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetLoginDetails_(Control_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAuthTokens_(Control_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PullArtifacts_(Control_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RegisterNode_(Control_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UnregisterNode_(Control_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListNodes_(Control_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListFederations_(Control_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ShowFederation_(Control_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Control::Stub::StartRun(::grpc::ClientContext* context, const ::flwr::proto::StartRunRequest& request, ::flwr::proto::StartRunResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::StartRunRequest, ::flwr::proto::StartRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StartRun_, context, request, response);
}

void Control::Stub::async::StartRun(::grpc::ClientContext* context, const ::flwr::proto::StartRunRequest* request, ::flwr::proto::StartRunResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::StartRunRequest, ::flwr::proto::StartRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartRun_, context, request, response, std::move(f));
}

void Control::Stub::async::StartRun(::grpc::ClientContext* context, const ::flwr::proto::StartRunRequest* request, ::flwr::proto::StartRunResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartRun_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::StartRunResponse>* Control::Stub::PrepareAsyncStartRunRaw(::grpc::ClientContext* context, const ::flwr::proto::StartRunRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::StartRunResponse, ::flwr::proto::StartRunRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StartRun_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::StartRunResponse>* Control::Stub::AsyncStartRunRaw(::grpc::ClientContext* context, const ::flwr::proto::StartRunRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartRunRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Control::Stub::StopRun(::grpc::ClientContext* context, const ::flwr::proto::StopRunRequest& request, ::flwr::proto::StopRunResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::StopRunRequest, ::flwr::proto::StopRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StopRun_, context, request, response);
}

void Control::Stub::async::StopRun(::grpc::ClientContext* context, const ::flwr::proto::StopRunRequest* request, ::flwr::proto::StopRunResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::StopRunRequest, ::flwr::proto::StopRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopRun_, context, request, response, std::move(f));
}

void Control::Stub::async::StopRun(::grpc::ClientContext* context, const ::flwr::proto::StopRunRequest* request, ::flwr::proto::StopRunResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopRun_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::StopRunResponse>* Control::Stub::PrepareAsyncStopRunRaw(::grpc::ClientContext* context, const ::flwr::proto::StopRunRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::StopRunResponse, ::flwr::proto::StopRunRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StopRun_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::StopRunResponse>* Control::Stub::AsyncStopRunRaw(::grpc::ClientContext* context, const ::flwr::proto::StopRunRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStopRunRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::flwr::proto::StreamLogsResponse>* Control::Stub::StreamLogsRaw(::grpc::ClientContext* context, const ::flwr::proto::StreamLogsRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::flwr::proto::StreamLogsResponse>::Create(channel_.get(), rpcmethod_StreamLogs_, context, request);
}

void Control::Stub::async::StreamLogs(::grpc::ClientContext* context, const ::flwr::proto::StreamLogsRequest* request, ::grpc::ClientReadReactor< ::flwr::proto::StreamLogsResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::flwr::proto::StreamLogsResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamLogs_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::flwr::proto::StreamLogsResponse>* Control::Stub::AsyncStreamLogsRaw(::grpc::ClientContext* context, const ::flwr::proto::StreamLogsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::flwr::proto::StreamLogsResponse>::Create(channel_.get(), cq, rpcmethod_StreamLogs_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::flwr::proto::StreamLogsResponse>* Control::Stub::PrepareAsyncStreamLogsRaw(::grpc::ClientContext* context, const ::flwr::proto::StreamLogsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::flwr::proto::StreamLogsResponse>::Create(channel_.get(), cq, rpcmethod_StreamLogs_, context, request, false, nullptr);
}

::grpc::Status Control::Stub::ListRuns(::grpc::ClientContext* context, const ::flwr::proto::ListRunsRequest& request, ::flwr::proto::ListRunsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::ListRunsRequest, ::flwr::proto::ListRunsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListRuns_, context, request, response);
}

void Control::Stub::async::ListRuns(::grpc::ClientContext* context, const ::flwr::proto::ListRunsRequest* request, ::flwr::proto::ListRunsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::ListRunsRequest, ::flwr::proto::ListRunsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListRuns_, context, request, response, std::move(f));
}

void Control::Stub::async::ListRuns(::grpc::ClientContext* context, const ::flwr::proto::ListRunsRequest* request, ::flwr::proto::ListRunsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListRuns_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::ListRunsResponse>* Control::Stub::PrepareAsyncListRunsRaw(::grpc::ClientContext* context, const ::flwr::proto::ListRunsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::ListRunsResponse, ::flwr::proto::ListRunsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListRuns_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::ListRunsResponse>* Control::Stub::AsyncListRunsRaw(::grpc::ClientContext* context, const ::flwr::proto::ListRunsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListRunsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Control::Stub::GetLoginDetails(::grpc::ClientContext* context, const ::flwr::proto::GetLoginDetailsRequest& request, ::flwr::proto::GetLoginDetailsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::GetLoginDetailsRequest, ::flwr::proto::GetLoginDetailsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetLoginDetails_, context, request, response);
}

void Control::Stub::async::GetLoginDetails(::grpc::ClientContext* context, const ::flwr::proto::GetLoginDetailsRequest* request, ::flwr::proto::GetLoginDetailsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::GetLoginDetailsRequest, ::flwr::proto::GetLoginDetailsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetLoginDetails_, context, request, response, std::move(f));
}

void Control::Stub::async::GetLoginDetails(::grpc::ClientContext* context, const ::flwr::proto::GetLoginDetailsRequest* request, ::flwr::proto::GetLoginDetailsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetLoginDetails_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::GetLoginDetailsResponse>* Control::Stub::PrepareAsyncGetLoginDetailsRaw(::grpc::ClientContext* context, const ::flwr::proto::GetLoginDetailsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::GetLoginDetailsResponse, ::flwr::proto::GetLoginDetailsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetLoginDetails_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::GetLoginDetailsResponse>* Control::Stub::AsyncGetLoginDetailsRaw(::grpc::ClientContext* context, const ::flwr::proto::GetLoginDetailsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetLoginDetailsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Control::Stub::GetAuthTokens(::grpc::ClientContext* context, const ::flwr::proto::GetAuthTokensRequest& request, ::flwr::proto::GetAuthTokensResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::GetAuthTokensRequest, ::flwr::proto::GetAuthTokensResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAuthTokens_, context, request, response);
}

void Control::Stub::async::GetAuthTokens(::grpc::ClientContext* context, const ::flwr::proto::GetAuthTokensRequest* request, ::flwr::proto::GetAuthTokensResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::GetAuthTokensRequest, ::flwr::proto::GetAuthTokensResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAuthTokens_, context, request, response, std::move(f));
}

void Control::Stub::async::GetAuthTokens(::grpc::ClientContext* context, const ::flwr::proto::GetAuthTokensRequest* request, ::flwr::proto::GetAuthTokensResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAuthTokens_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::GetAuthTokensResponse>* Control::Stub::PrepareAsyncGetAuthTokensRaw(::grpc::ClientContext* context, const ::flwr::proto::GetAuthTokensRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::GetAuthTokensResponse, ::flwr::proto::GetAuthTokensRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAuthTokens_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::GetAuthTokensResponse>* Control::Stub::AsyncGetAuthTokensRaw(::grpc::ClientContext* context, const ::flwr::proto::GetAuthTokensRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAuthTokensRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Control::Stub::PullArtifacts(::grpc::ClientContext* context, const ::flwr::proto::PullArtifactsRequest& request, ::flwr::proto::PullArtifactsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::PullArtifactsRequest, ::flwr::proto::PullArtifactsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PullArtifacts_, context, request, response);
}

void Control::Stub::async::PullArtifacts(::grpc::ClientContext* context, const ::flwr::proto::PullArtifactsRequest* request, ::flwr::proto::PullArtifactsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::PullArtifactsRequest, ::flwr::proto::PullArtifactsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PullArtifacts_, context, request, response, std::move(f));
}

void Control::Stub::async::PullArtifacts(::grpc::ClientContext* context, const ::flwr::proto::PullArtifactsRequest* request, ::flwr::proto::PullArtifactsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PullArtifacts_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PullArtifactsResponse>* Control::Stub::PrepareAsyncPullArtifactsRaw(::grpc::ClientContext* context, const ::flwr::proto::PullArtifactsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::PullArtifactsResponse, ::flwr::proto::PullArtifactsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PullArtifacts_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PullArtifactsResponse>* Control::Stub::AsyncPullArtifactsRaw(::grpc::ClientContext* context, const ::flwr::proto::PullArtifactsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPullArtifactsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Control::Stub::RegisterNode(::grpc::ClientContext* context, const ::flwr::proto::RegisterNodeRequest& request, ::flwr::proto::RegisterNodeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::RegisterNodeRequest, ::flwr::proto::RegisterNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterNode_, context, request, response);
}

void Control::Stub::async::RegisterNode(::grpc::ClientContext* context, const ::flwr::proto::RegisterNodeRequest* request, ::flwr::proto::RegisterNodeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::RegisterNodeRequest, ::flwr::proto::RegisterNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterNode_, context, request, response, std::move(f));
}

void Control::Stub::async::RegisterNode(::grpc::ClientContext* context, const ::flwr::proto::RegisterNodeRequest* request, ::flwr::proto::RegisterNodeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterNode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::RegisterNodeResponse>* Control::Stub::PrepareAsyncRegisterNodeRaw(::grpc::ClientContext* context, const ::flwr::proto::RegisterNodeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::RegisterNodeResponse, ::flwr::proto::RegisterNodeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterNode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::RegisterNodeResponse>* Control::Stub::AsyncRegisterNodeRaw(::grpc::ClientContext* context, const ::flwr::proto::RegisterNodeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterNodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Control::Stub::UnregisterNode(::grpc::ClientContext* context, const ::flwr::proto::UnregisterNodeRequest& request, ::flwr::proto::UnregisterNodeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::UnregisterNodeRequest, ::flwr::proto::UnregisterNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UnregisterNode_, context, request, response);
}

void Control::Stub::async::UnregisterNode(::grpc::ClientContext* context, const ::flwr::proto::UnregisterNodeRequest* request, ::flwr::proto::UnregisterNodeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::UnregisterNodeRequest, ::flwr::proto::UnregisterNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnregisterNode_, context, request, response, std::move(f));
}

void Control::Stub::async::UnregisterNode(::grpc::ClientContext* context, const ::flwr::proto::UnregisterNodeRequest* request, ::flwr::proto::UnregisterNodeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnregisterNode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::UnregisterNodeResponse>* Control::Stub::PrepareAsyncUnregisterNodeRaw(::grpc::ClientContext* context, const ::flwr::proto::UnregisterNodeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::UnregisterNodeResponse, ::flwr::proto::UnregisterNodeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UnregisterNode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::UnregisterNodeResponse>* Control::Stub::AsyncUnregisterNodeRaw(::grpc::ClientContext* context, const ::flwr::proto::UnregisterNodeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUnregisterNodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Control::Stub::ListNodes(::grpc::ClientContext* context, const ::flwr::proto::ListNodesRequest& request, ::flwr::proto::ListNodesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::ListNodesRequest, ::flwr::proto::ListNodesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListNodes_, context, request, response);
}

void Control::Stub::async::ListNodes(::grpc::ClientContext* context, const ::flwr::proto::ListNodesRequest* request, ::flwr::proto::ListNodesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::ListNodesRequest, ::flwr::proto::ListNodesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListNodes_, context, request, response, std::move(f));
}

void Control::Stub::async::ListNodes(::grpc::ClientContext* context, const ::flwr::proto::ListNodesRequest* request, ::flwr::proto::ListNodesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListNodes_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::ListNodesResponse>* Control::Stub::PrepareAsyncListNodesRaw(::grpc::ClientContext* context, const ::flwr::proto::ListNodesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::ListNodesResponse, ::flwr::proto::ListNodesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListNodes_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::ListNodesResponse>* Control::Stub::AsyncListNodesRaw(::grpc::ClientContext* context, const ::flwr::proto::ListNodesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListNodesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Control::Stub::ListFederations(::grpc::ClientContext* context, const ::flwr::proto::ListFederationsRequest& request, ::flwr::proto::ListFederationsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::ListFederationsRequest, ::flwr::proto::ListFederationsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListFederations_, context, request, response);
}

void Control::Stub::async::ListFederations(::grpc::ClientContext* context, const ::flwr::proto::ListFederationsRequest* request, ::flwr::proto::ListFederationsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::ListFederationsRequest, ::flwr::proto::ListFederationsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListFederations_, context, request, response, std::move(f));
}

void Control::Stub::async::ListFederations(::grpc::ClientContext* context, const ::flwr::proto::ListFederationsRequest* request, ::flwr::proto::ListFederationsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListFederations_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::ListFederationsResponse>* Control::Stub::PrepareAsyncListFederationsRaw(::grpc::ClientContext* context, const ::flwr::proto::ListFederationsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::ListFederationsResponse, ::flwr::proto::ListFederationsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListFederations_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::ListFederationsResponse>* Control::Stub::AsyncListFederationsRaw(::grpc::ClientContext* context, const ::flwr::proto::ListFederationsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListFederationsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Control::Stub::ShowFederation(::grpc::ClientContext* context, const ::flwr::proto::ShowFederationRequest& request, ::flwr::proto::ShowFederationResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::ShowFederationRequest, ::flwr::proto::ShowFederationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ShowFederation_, context, request, response);
}

void Control::Stub::async::ShowFederation(::grpc::ClientContext* context, const ::flwr::proto::ShowFederationRequest* request, ::flwr::proto::ShowFederationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::ShowFederationRequest, ::flwr::proto::ShowFederationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ShowFederation_, context, request, response, std::move(f));
}

void Control::Stub::async::ShowFederation(::grpc::ClientContext* context, const ::flwr::proto::ShowFederationRequest* request, ::flwr::proto::ShowFederationResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ShowFederation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::ShowFederationResponse>* Control::Stub::PrepareAsyncShowFederationRaw(::grpc::ClientContext* context, const ::flwr::proto::ShowFederationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::ShowFederationResponse, ::flwr::proto::ShowFederationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ShowFederation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::ShowFederationResponse>* Control::Stub::AsyncShowFederationRaw(::grpc::ClientContext* context, const ::flwr::proto::ShowFederationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncShowFederationRaw(context, request, cq);
  result->StartCall();
  return result;
}

Control::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Control_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Control::Service, ::flwr::proto::StartRunRequest, ::flwr::proto::StartRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Control::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::StartRunRequest* req,
             ::flwr::proto::StartRunResponse* resp) {
               return service->StartRun(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Control_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Control::Service, ::flwr::proto::StopRunRequest, ::flwr::proto::StopRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Control::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::StopRunRequest* req,
             ::flwr::proto::StopRunResponse* resp) {
               return service->StopRun(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Control_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Control::Service, ::flwr::proto::StreamLogsRequest, ::flwr::proto::StreamLogsResponse>(
          [](Control::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::StreamLogsRequest* req,
             ::grpc::ServerWriter<::flwr::proto::StreamLogsResponse>* writer) {
               return service->StreamLogs(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Control_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Control::Service, ::flwr::proto::ListRunsRequest, ::flwr::proto::ListRunsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Control::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::ListRunsRequest* req,
             ::flwr::proto::ListRunsResponse* resp) {
               return service->ListRuns(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Control_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Control::Service, ::flwr::proto::GetLoginDetailsRequest, ::flwr::proto::GetLoginDetailsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Control::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::GetLoginDetailsRequest* req,
             ::flwr::proto::GetLoginDetailsResponse* resp) {
               return service->GetLoginDetails(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Control_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Control::Service, ::flwr::proto::GetAuthTokensRequest, ::flwr::proto::GetAuthTokensResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Control::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::GetAuthTokensRequest* req,
             ::flwr::proto::GetAuthTokensResponse* resp) {
               return service->GetAuthTokens(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Control_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Control::Service, ::flwr::proto::PullArtifactsRequest, ::flwr::proto::PullArtifactsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Control::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::PullArtifactsRequest* req,
             ::flwr::proto::PullArtifactsResponse* resp) {
               return service->PullArtifacts(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Control_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Control::Service, ::flwr::proto::RegisterNodeRequest, ::flwr::proto::RegisterNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Control::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::RegisterNodeRequest* req,
             ::flwr::proto::RegisterNodeResponse* resp) {
               return service->RegisterNode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Control_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Control::Service, ::flwr::proto::UnregisterNodeRequest, ::flwr::proto::UnregisterNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Control::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::UnregisterNodeRequest* req,
             ::flwr::proto::UnregisterNodeResponse* resp) {
               return service->UnregisterNode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Control_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Control::Service, ::flwr::proto::ListNodesRequest, ::flwr::proto::ListNodesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Control::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::ListNodesRequest* req,
             ::flwr::proto::ListNodesResponse* resp) {
               return service->ListNodes(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Control_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Control::Service, ::flwr::proto::ListFederationsRequest, ::flwr::proto::ListFederationsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Control::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::ListFederationsRequest* req,
             ::flwr::proto::ListFederationsResponse* resp) {
               return service->ListFederations(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Control_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Control::Service, ::flwr::proto::ShowFederationRequest, ::flwr::proto::ShowFederationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Control::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::ShowFederationRequest* req,
             ::flwr::proto::ShowFederationResponse* resp) {
               return service->ShowFederation(ctx, req, resp);
             }, this)));
}

Control::Service::~Service() {
}

::grpc::Status Control::Service::StartRun(::grpc::ServerContext* context, const ::flwr::proto::StartRunRequest* request, ::flwr::proto::StartRunResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Control::Service::StopRun(::grpc::ServerContext* context, const ::flwr::proto::StopRunRequest* request, ::flwr::proto::StopRunResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Control::Service::StreamLogs(::grpc::ServerContext* context, const ::flwr::proto::StreamLogsRequest* request, ::grpc::ServerWriter< ::flwr::proto::StreamLogsResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Control::Service::ListRuns(::grpc::ServerContext* context, const ::flwr::proto::ListRunsRequest* request, ::flwr::proto::ListRunsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Control::Service::GetLoginDetails(::grpc::ServerContext* context, const ::flwr::proto::GetLoginDetailsRequest* request, ::flwr::proto::GetLoginDetailsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Control::Service::GetAuthTokens(::grpc::ServerContext* context, const ::flwr::proto::GetAuthTokensRequest* request, ::flwr::proto::GetAuthTokensResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Control::Service::PullArtifacts(::grpc::ServerContext* context, const ::flwr::proto::PullArtifactsRequest* request, ::flwr::proto::PullArtifactsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Control::Service::RegisterNode(::grpc::ServerContext* context, const ::flwr::proto::RegisterNodeRequest* request, ::flwr::proto::RegisterNodeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Control::Service::UnregisterNode(::grpc::ServerContext* context, const ::flwr::proto::UnregisterNodeRequest* request, ::flwr::proto::UnregisterNodeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Control::Service::ListNodes(::grpc::ServerContext* context, const ::flwr::proto::ListNodesRequest* request, ::flwr::proto::ListNodesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Control::Service::ListFederations(::grpc::ServerContext* context, const ::flwr::proto::ListFederationsRequest* request, ::flwr::proto::ListFederationsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Control::Service::ShowFederation(::grpc::ServerContext* context, const ::flwr::proto::ShowFederationRequest* request, ::flwr::proto::ShowFederationResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace flwr
}  // namespace proto

