// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flwr/proto/fab.proto

#include "flwr/proto/fab.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace flwr {
namespace proto {
PROTOBUF_CONSTEXPR Fab_VerificationsEntry_DoNotUse::Fab_VerificationsEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct Fab_VerificationsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Fab_VerificationsEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Fab_VerificationsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    Fab_VerificationsEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Fab_VerificationsEntry_DoNotUseDefaultTypeInternal _Fab_VerificationsEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR Fab::Fab(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.verifications_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.hash_str_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.content_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FabDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FabDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FabDefaultTypeInternal() {}
  union {
    Fab _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FabDefaultTypeInternal _Fab_default_instance_;
PROTOBUF_CONSTEXPR GetFabRequest::GetFabRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.hash_str_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.node_)*/nullptr
  , /*decltype(_impl_.run_id_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetFabRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetFabRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetFabRequestDefaultTypeInternal() {}
  union {
    GetFabRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetFabRequestDefaultTypeInternal _GetFabRequest_default_instance_;
PROTOBUF_CONSTEXPR GetFabResponse::GetFabResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.fab_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetFabResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetFabResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetFabResponseDefaultTypeInternal() {}
  union {
    GetFabResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetFabResponseDefaultTypeInternal _GetFabResponse_default_instance_;
}  // namespace proto
}  // namespace flwr
static ::_pb::Metadata file_level_metadata_flwr_2fproto_2ffab_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_flwr_2fproto_2ffab_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_flwr_2fproto_2ffab_2eproto = nullptr;

const uint32_t TableStruct_flwr_2fproto_2ffab_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::flwr::proto::Fab_VerificationsEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::flwr::proto::Fab_VerificationsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::Fab_VerificationsEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::flwr::proto::Fab_VerificationsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::Fab, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::Fab, _impl_.hash_str_),
  PROTOBUF_FIELD_OFFSET(::flwr::proto::Fab, _impl_.content_),
  PROTOBUF_FIELD_OFFSET(::flwr::proto::Fab, _impl_.verifications_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::GetFabRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::GetFabRequest, _impl_.node_),
  PROTOBUF_FIELD_OFFSET(::flwr::proto::GetFabRequest, _impl_.hash_str_),
  PROTOBUF_FIELD_OFFSET(::flwr::proto::GetFabRequest, _impl_.run_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::GetFabResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::GetFabResponse, _impl_.fab_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::flwr::proto::Fab_VerificationsEntry_DoNotUse)},
  { 10, -1, -1, sizeof(::flwr::proto::Fab)},
  { 19, -1, -1, sizeof(::flwr::proto::GetFabRequest)},
  { 28, -1, -1, sizeof(::flwr::proto::GetFabResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::flwr::proto::_Fab_VerificationsEntry_DoNotUse_default_instance_._instance,
  &::flwr::proto::_Fab_default_instance_._instance,
  &::flwr::proto::_GetFabRequest_default_instance_._instance,
  &::flwr::proto::_GetFabResponse_default_instance_._instance,
};

const char descriptor_table_protodef_flwr_2fproto_2ffab_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024flwr/proto/fab.proto\022\nflwr.proto\032\025flwr"
  "/proto/node.proto\"\231\001\n\003Fab\022\020\n\010hash_str\030\001 "
  "\001(\t\022\017\n\007content\030\002 \001(\014\0229\n\rverifications\030\003 "
  "\003(\0132\".flwr.proto.Fab.VerificationsEntry\032"
  "4\n\022VerificationsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va"
  "lue\030\002 \001(\t:\0028\001\"Q\n\rGetFabRequest\022\036\n\004node\030\001"
  " \001(\0132\020.flwr.proto.Node\022\020\n\010hash_str\030\002 \001(\t"
  "\022\016\n\006run_id\030\003 \001(\004\".\n\016GetFabResponse\022\034\n\003fa"
  "b\030\001 \001(\0132\017.flwr.proto.Fabb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_flwr_2fproto_2ffab_2eproto_deps[1] = {
  &::descriptor_table_flwr_2fproto_2fnode_2eproto,
};
static ::_pbi::once_flag descriptor_table_flwr_2fproto_2ffab_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_flwr_2fproto_2ffab_2eproto = {
    false, false, 352, descriptor_table_protodef_flwr_2fproto_2ffab_2eproto,
    "flwr/proto/fab.proto",
    &descriptor_table_flwr_2fproto_2ffab_2eproto_once, descriptor_table_flwr_2fproto_2ffab_2eproto_deps, 1, 4,
    schemas, file_default_instances, TableStruct_flwr_2fproto_2ffab_2eproto::offsets,
    file_level_metadata_flwr_2fproto_2ffab_2eproto, file_level_enum_descriptors_flwr_2fproto_2ffab_2eproto,
    file_level_service_descriptors_flwr_2fproto_2ffab_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_flwr_2fproto_2ffab_2eproto_getter() {
  return &descriptor_table_flwr_2fproto_2ffab_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_flwr_2fproto_2ffab_2eproto(&descriptor_table_flwr_2fproto_2ffab_2eproto);
namespace flwr {
namespace proto {

// ===================================================================

Fab_VerificationsEntry_DoNotUse::Fab_VerificationsEntry_DoNotUse() {}
Fab_VerificationsEntry_DoNotUse::Fab_VerificationsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void Fab_VerificationsEntry_DoNotUse::MergeFrom(const Fab_VerificationsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata Fab_VerificationsEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_flwr_2fproto_2ffab_2eproto_getter, &descriptor_table_flwr_2fproto_2ffab_2eproto_once,
      file_level_metadata_flwr_2fproto_2ffab_2eproto[0]);
}

// ===================================================================

class Fab::_Internal {
 public:
};

Fab::Fab(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &Fab::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:flwr.proto.Fab)
}
Fab::Fab(const Fab& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Fab* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.verifications_)*/{}
    , decltype(_impl_.hash_str_){}
    , decltype(_impl_.content_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.verifications_.MergeFrom(from._impl_.verifications_);
  _impl_.hash_str_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hash_str_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_hash_str().empty()) {
    _this->_impl_.hash_str_.Set(from._internal_hash_str(), 
      _this->GetArenaForAllocation());
  }
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_content().empty()) {
    _this->_impl_.content_.Set(from._internal_content(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:flwr.proto.Fab)
}

inline void Fab::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.verifications_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_.hash_str_){}
    , decltype(_impl_.content_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.hash_str_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hash_str_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Fab::~Fab() {
  // @@protoc_insertion_point(destructor:flwr.proto.Fab)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void Fab::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.verifications_.Destruct();
  _impl_.verifications_.~MapField();
  _impl_.hash_str_.Destroy();
  _impl_.content_.Destroy();
}

void Fab::ArenaDtor(void* object) {
  Fab* _this = reinterpret_cast< Fab* >(object);
  _this->_impl_.verifications_.Destruct();
}
void Fab::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Fab::Clear() {
// @@protoc_insertion_point(message_clear_start:flwr.proto.Fab)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.verifications_.Clear();
  _impl_.hash_str_.ClearToEmpty();
  _impl_.content_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Fab::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string hash_str = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_hash_str();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "flwr.proto.Fab.hash_str"));
        } else
          goto handle_unusual;
        continue;
      // bytes content = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_content();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // map<string, string> verifications = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.verifications_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Fab::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:flwr.proto.Fab)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string hash_str = 1;
  if (!this->_internal_hash_str().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_hash_str().data(), static_cast<int>(this->_internal_hash_str().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "flwr.proto.Fab.hash_str");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_hash_str(), target);
  }

  // bytes content = 2;
  if (!this->_internal_content().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_content(), target);
  }

  // map<string, string> verifications = 3;
  if (!this->_internal_verifications().empty()) {
    using MapType = ::_pb::Map<std::string, std::string>;
    using WireHelper = Fab_VerificationsEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_verifications();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "flwr.proto.Fab.VerificationsEntry.key");
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.second.data(), static_cast<int>(entry.second.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "flwr.proto.Fab.VerificationsEntry.value");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:flwr.proto.Fab)
  return target;
}

size_t Fab::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:flwr.proto.Fab)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, string> verifications = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_verifications_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_verifications().begin();
      it != this->_internal_verifications().end(); ++it) {
    total_size += Fab_VerificationsEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // string hash_str = 1;
  if (!this->_internal_hash_str().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_hash_str());
  }

  // bytes content = 2;
  if (!this->_internal_content().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_content());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Fab::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Fab::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Fab::GetClassData() const { return &_class_data_; }


void Fab::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Fab*>(&to_msg);
  auto& from = static_cast<const Fab&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:flwr.proto.Fab)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.verifications_.MergeFrom(from._impl_.verifications_);
  if (!from._internal_hash_str().empty()) {
    _this->_internal_set_hash_str(from._internal_hash_str());
  }
  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Fab::CopyFrom(const Fab& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flwr.proto.Fab)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Fab::IsInitialized() const {
  return true;
}

void Fab::InternalSwap(Fab* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.verifications_.InternalSwap(&other->_impl_.verifications_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.hash_str_, lhs_arena,
      &other->_impl_.hash_str_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.content_, lhs_arena,
      &other->_impl_.content_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Fab::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_flwr_2fproto_2ffab_2eproto_getter, &descriptor_table_flwr_2fproto_2ffab_2eproto_once,
      file_level_metadata_flwr_2fproto_2ffab_2eproto[1]);
}

// ===================================================================

class GetFabRequest::_Internal {
 public:
  static const ::flwr::proto::Node& node(const GetFabRequest* msg);
};

const ::flwr::proto::Node&
GetFabRequest::_Internal::node(const GetFabRequest* msg) {
  return *msg->_impl_.node_;
}
void GetFabRequest::clear_node() {
  if (GetArenaForAllocation() == nullptr && _impl_.node_ != nullptr) {
    delete _impl_.node_;
  }
  _impl_.node_ = nullptr;
}
GetFabRequest::GetFabRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:flwr.proto.GetFabRequest)
}
GetFabRequest::GetFabRequest(const GetFabRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetFabRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.hash_str_){}
    , decltype(_impl_.node_){nullptr}
    , decltype(_impl_.run_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.hash_str_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hash_str_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_hash_str().empty()) {
    _this->_impl_.hash_str_.Set(from._internal_hash_str(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_node()) {
    _this->_impl_.node_ = new ::flwr::proto::Node(*from._impl_.node_);
  }
  _this->_impl_.run_id_ = from._impl_.run_id_;
  // @@protoc_insertion_point(copy_constructor:flwr.proto.GetFabRequest)
}

inline void GetFabRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.hash_str_){}
    , decltype(_impl_.node_){nullptr}
    , decltype(_impl_.run_id_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.hash_str_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hash_str_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GetFabRequest::~GetFabRequest() {
  // @@protoc_insertion_point(destructor:flwr.proto.GetFabRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetFabRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.hash_str_.Destroy();
  if (this != internal_default_instance()) delete _impl_.node_;
}

void GetFabRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetFabRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:flwr.proto.GetFabRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.hash_str_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.node_ != nullptr) {
    delete _impl_.node_;
  }
  _impl_.node_ = nullptr;
  _impl_.run_id_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetFabRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .flwr.proto.Node node = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_node(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string hash_str = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_hash_str();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "flwr.proto.GetFabRequest.hash_str"));
        } else
          goto handle_unusual;
        continue;
      // uint64 run_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.run_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetFabRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:flwr.proto.GetFabRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .flwr.proto.Node node = 1;
  if (this->_internal_has_node()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::node(this),
        _Internal::node(this).GetCachedSize(), target, stream);
  }

  // string hash_str = 2;
  if (!this->_internal_hash_str().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_hash_str().data(), static_cast<int>(this->_internal_hash_str().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "flwr.proto.GetFabRequest.hash_str");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_hash_str(), target);
  }

  // uint64 run_id = 3;
  if (this->_internal_run_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_run_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:flwr.proto.GetFabRequest)
  return target;
}

size_t GetFabRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:flwr.proto.GetFabRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string hash_str = 2;
  if (!this->_internal_hash_str().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_hash_str());
  }

  // .flwr.proto.Node node = 1;
  if (this->_internal_has_node()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.node_);
  }

  // uint64 run_id = 3;
  if (this->_internal_run_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_run_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetFabRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetFabRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetFabRequest::GetClassData() const { return &_class_data_; }


void GetFabRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetFabRequest*>(&to_msg);
  auto& from = static_cast<const GetFabRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:flwr.proto.GetFabRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_hash_str().empty()) {
    _this->_internal_set_hash_str(from._internal_hash_str());
  }
  if (from._internal_has_node()) {
    _this->_internal_mutable_node()->::flwr::proto::Node::MergeFrom(
        from._internal_node());
  }
  if (from._internal_run_id() != 0) {
    _this->_internal_set_run_id(from._internal_run_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetFabRequest::CopyFrom(const GetFabRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flwr.proto.GetFabRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetFabRequest::IsInitialized() const {
  return true;
}

void GetFabRequest::InternalSwap(GetFabRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.hash_str_, lhs_arena,
      &other->_impl_.hash_str_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetFabRequest, _impl_.run_id_)
      + sizeof(GetFabRequest::_impl_.run_id_)
      - PROTOBUF_FIELD_OFFSET(GetFabRequest, _impl_.node_)>(
          reinterpret_cast<char*>(&_impl_.node_),
          reinterpret_cast<char*>(&other->_impl_.node_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GetFabRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_flwr_2fproto_2ffab_2eproto_getter, &descriptor_table_flwr_2fproto_2ffab_2eproto_once,
      file_level_metadata_flwr_2fproto_2ffab_2eproto[2]);
}

// ===================================================================

class GetFabResponse::_Internal {
 public:
  static const ::flwr::proto::Fab& fab(const GetFabResponse* msg);
};

const ::flwr::proto::Fab&
GetFabResponse::_Internal::fab(const GetFabResponse* msg) {
  return *msg->_impl_.fab_;
}
GetFabResponse::GetFabResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:flwr.proto.GetFabResponse)
}
GetFabResponse::GetFabResponse(const GetFabResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetFabResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.fab_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_fab()) {
    _this->_impl_.fab_ = new ::flwr::proto::Fab(*from._impl_.fab_);
  }
  // @@protoc_insertion_point(copy_constructor:flwr.proto.GetFabResponse)
}

inline void GetFabResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.fab_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetFabResponse::~GetFabResponse() {
  // @@protoc_insertion_point(destructor:flwr.proto.GetFabResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetFabResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.fab_;
}

void GetFabResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetFabResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:flwr.proto.GetFabResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.fab_ != nullptr) {
    delete _impl_.fab_;
  }
  _impl_.fab_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetFabResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .flwr.proto.Fab fab = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_fab(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetFabResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:flwr.proto.GetFabResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .flwr.proto.Fab fab = 1;
  if (this->_internal_has_fab()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::fab(this),
        _Internal::fab(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:flwr.proto.GetFabResponse)
  return target;
}

size_t GetFabResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:flwr.proto.GetFabResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .flwr.proto.Fab fab = 1;
  if (this->_internal_has_fab()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.fab_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetFabResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetFabResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetFabResponse::GetClassData() const { return &_class_data_; }


void GetFabResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetFabResponse*>(&to_msg);
  auto& from = static_cast<const GetFabResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:flwr.proto.GetFabResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_fab()) {
    _this->_internal_mutable_fab()->::flwr::proto::Fab::MergeFrom(
        from._internal_fab());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetFabResponse::CopyFrom(const GetFabResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flwr.proto.GetFabResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetFabResponse::IsInitialized() const {
  return true;
}

void GetFabResponse::InternalSwap(GetFabResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.fab_, other->_impl_.fab_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetFabResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_flwr_2fproto_2ffab_2eproto_getter, &descriptor_table_flwr_2fproto_2ffab_2eproto_once,
      file_level_metadata_flwr_2fproto_2ffab_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace flwr
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::flwr::proto::Fab_VerificationsEntry_DoNotUse*
Arena::CreateMaybeMessage< ::flwr::proto::Fab_VerificationsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::flwr::proto::Fab_VerificationsEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::flwr::proto::Fab*
Arena::CreateMaybeMessage< ::flwr::proto::Fab >(Arena* arena) {
  return Arena::CreateMessageInternal< ::flwr::proto::Fab >(arena);
}
template<> PROTOBUF_NOINLINE ::flwr::proto::GetFabRequest*
Arena::CreateMaybeMessage< ::flwr::proto::GetFabRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::flwr::proto::GetFabRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::flwr::proto::GetFabResponse*
Arena::CreateMaybeMessage< ::flwr::proto::GetFabResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::flwr::proto::GetFabResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
