// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flwr/proto/federation.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_flwr_2fproto_2ffederation_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_flwr_2fproto_2ffederation_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "flwr/proto/run.pb.h"
#include "flwr/proto/node.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_flwr_2fproto_2ffederation_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_flwr_2fproto_2ffederation_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_flwr_2fproto_2ffederation_2eproto;
namespace flwr {
namespace proto {
class Federation;
struct FederationDefaultTypeInternal;
extern FederationDefaultTypeInternal _Federation_default_instance_;
}  // namespace proto
}  // namespace flwr
PROTOBUF_NAMESPACE_OPEN
template<> ::flwr::proto::Federation* Arena::CreateMaybeMessage<::flwr::proto::Federation>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace flwr {
namespace proto {

// ===================================================================

class Federation final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:flwr.proto.Federation) */ {
 public:
  inline Federation() : Federation(nullptr) {}
  ~Federation() override;
  explicit PROTOBUF_CONSTEXPR Federation(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Federation(const Federation& from);
  Federation(Federation&& from) noexcept
    : Federation() {
    *this = ::std::move(from);
  }

  inline Federation& operator=(const Federation& from) {
    CopyFrom(from);
    return *this;
  }
  inline Federation& operator=(Federation&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Federation& default_instance() {
    return *internal_default_instance();
  }
  static inline const Federation* internal_default_instance() {
    return reinterpret_cast<const Federation*>(
               &_Federation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Federation& a, Federation& b) {
    a.Swap(&b);
  }
  inline void Swap(Federation* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Federation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Federation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Federation>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Federation& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Federation& from) {
    Federation::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Federation* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "flwr.proto.Federation";
  }
  protected:
  explicit Federation(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMemberAidsFieldNumber = 2,
    kNodesFieldNumber = 3,
    kRunsFieldNumber = 4,
    kNameFieldNumber = 1,
  };
  // repeated string member_aids = 2;
  int member_aids_size() const;
  private:
  int _internal_member_aids_size() const;
  public:
  void clear_member_aids();
  const std::string& member_aids(int index) const;
  std::string* mutable_member_aids(int index);
  void set_member_aids(int index, const std::string& value);
  void set_member_aids(int index, std::string&& value);
  void set_member_aids(int index, const char* value);
  void set_member_aids(int index, const char* value, size_t size);
  std::string* add_member_aids();
  void add_member_aids(const std::string& value);
  void add_member_aids(std::string&& value);
  void add_member_aids(const char* value);
  void add_member_aids(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& member_aids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_member_aids();
  private:
  const std::string& _internal_member_aids(int index) const;
  std::string* _internal_add_member_aids();
  public:

  // repeated .flwr.proto.NodeInfo nodes = 3;
  int nodes_size() const;
  private:
  int _internal_nodes_size() const;
  public:
  void clear_nodes();
  ::flwr::proto::NodeInfo* mutable_nodes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::flwr::proto::NodeInfo >*
      mutable_nodes();
  private:
  const ::flwr::proto::NodeInfo& _internal_nodes(int index) const;
  ::flwr::proto::NodeInfo* _internal_add_nodes();
  public:
  const ::flwr::proto::NodeInfo& nodes(int index) const;
  ::flwr::proto::NodeInfo* add_nodes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::flwr::proto::NodeInfo >&
      nodes() const;

  // repeated .flwr.proto.Run runs = 4;
  int runs_size() const;
  private:
  int _internal_runs_size() const;
  public:
  void clear_runs();
  ::flwr::proto::Run* mutable_runs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::flwr::proto::Run >*
      mutable_runs();
  private:
  const ::flwr::proto::Run& _internal_runs(int index) const;
  ::flwr::proto::Run* _internal_add_runs();
  public:
  const ::flwr::proto::Run& runs(int index) const;
  ::flwr::proto::Run* add_runs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::flwr::proto::Run >&
      runs() const;

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:flwr.proto.Federation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> member_aids_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::flwr::proto::NodeInfo > nodes_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::flwr::proto::Run > runs_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_flwr_2fproto_2ffederation_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Federation

// string name = 1;
inline void Federation::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Federation::name() const {
  // @@protoc_insertion_point(field_get:flwr.proto.Federation.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Federation::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:flwr.proto.Federation.name)
}
inline std::string* Federation::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:flwr.proto.Federation.name)
  return _s;
}
inline const std::string& Federation::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Federation::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Federation::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Federation::release_name() {
  // @@protoc_insertion_point(field_release:flwr.proto.Federation.name)
  return _impl_.name_.Release();
}
inline void Federation::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:flwr.proto.Federation.name)
}

// repeated string member_aids = 2;
inline int Federation::_internal_member_aids_size() const {
  return _impl_.member_aids_.size();
}
inline int Federation::member_aids_size() const {
  return _internal_member_aids_size();
}
inline void Federation::clear_member_aids() {
  _impl_.member_aids_.Clear();
}
inline std::string* Federation::add_member_aids() {
  std::string* _s = _internal_add_member_aids();
  // @@protoc_insertion_point(field_add_mutable:flwr.proto.Federation.member_aids)
  return _s;
}
inline const std::string& Federation::_internal_member_aids(int index) const {
  return _impl_.member_aids_.Get(index);
}
inline const std::string& Federation::member_aids(int index) const {
  // @@protoc_insertion_point(field_get:flwr.proto.Federation.member_aids)
  return _internal_member_aids(index);
}
inline std::string* Federation::mutable_member_aids(int index) {
  // @@protoc_insertion_point(field_mutable:flwr.proto.Federation.member_aids)
  return _impl_.member_aids_.Mutable(index);
}
inline void Federation::set_member_aids(int index, const std::string& value) {
  _impl_.member_aids_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:flwr.proto.Federation.member_aids)
}
inline void Federation::set_member_aids(int index, std::string&& value) {
  _impl_.member_aids_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:flwr.proto.Federation.member_aids)
}
inline void Federation::set_member_aids(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.member_aids_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:flwr.proto.Federation.member_aids)
}
inline void Federation::set_member_aids(int index, const char* value, size_t size) {
  _impl_.member_aids_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:flwr.proto.Federation.member_aids)
}
inline std::string* Federation::_internal_add_member_aids() {
  return _impl_.member_aids_.Add();
}
inline void Federation::add_member_aids(const std::string& value) {
  _impl_.member_aids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:flwr.proto.Federation.member_aids)
}
inline void Federation::add_member_aids(std::string&& value) {
  _impl_.member_aids_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:flwr.proto.Federation.member_aids)
}
inline void Federation::add_member_aids(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.member_aids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:flwr.proto.Federation.member_aids)
}
inline void Federation::add_member_aids(const char* value, size_t size) {
  _impl_.member_aids_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:flwr.proto.Federation.member_aids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Federation::member_aids() const {
  // @@protoc_insertion_point(field_list:flwr.proto.Federation.member_aids)
  return _impl_.member_aids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Federation::mutable_member_aids() {
  // @@protoc_insertion_point(field_mutable_list:flwr.proto.Federation.member_aids)
  return &_impl_.member_aids_;
}

// repeated .flwr.proto.NodeInfo nodes = 3;
inline int Federation::_internal_nodes_size() const {
  return _impl_.nodes_.size();
}
inline int Federation::nodes_size() const {
  return _internal_nodes_size();
}
inline ::flwr::proto::NodeInfo* Federation::mutable_nodes(int index) {
  // @@protoc_insertion_point(field_mutable:flwr.proto.Federation.nodes)
  return _impl_.nodes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::flwr::proto::NodeInfo >*
Federation::mutable_nodes() {
  // @@protoc_insertion_point(field_mutable_list:flwr.proto.Federation.nodes)
  return &_impl_.nodes_;
}
inline const ::flwr::proto::NodeInfo& Federation::_internal_nodes(int index) const {
  return _impl_.nodes_.Get(index);
}
inline const ::flwr::proto::NodeInfo& Federation::nodes(int index) const {
  // @@protoc_insertion_point(field_get:flwr.proto.Federation.nodes)
  return _internal_nodes(index);
}
inline ::flwr::proto::NodeInfo* Federation::_internal_add_nodes() {
  return _impl_.nodes_.Add();
}
inline ::flwr::proto::NodeInfo* Federation::add_nodes() {
  ::flwr::proto::NodeInfo* _add = _internal_add_nodes();
  // @@protoc_insertion_point(field_add:flwr.proto.Federation.nodes)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::flwr::proto::NodeInfo >&
Federation::nodes() const {
  // @@protoc_insertion_point(field_list:flwr.proto.Federation.nodes)
  return _impl_.nodes_;
}

// repeated .flwr.proto.Run runs = 4;
inline int Federation::_internal_runs_size() const {
  return _impl_.runs_.size();
}
inline int Federation::runs_size() const {
  return _internal_runs_size();
}
inline ::flwr::proto::Run* Federation::mutable_runs(int index) {
  // @@protoc_insertion_point(field_mutable:flwr.proto.Federation.runs)
  return _impl_.runs_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::flwr::proto::Run >*
Federation::mutable_runs() {
  // @@protoc_insertion_point(field_mutable_list:flwr.proto.Federation.runs)
  return &_impl_.runs_;
}
inline const ::flwr::proto::Run& Federation::_internal_runs(int index) const {
  return _impl_.runs_.Get(index);
}
inline const ::flwr::proto::Run& Federation::runs(int index) const {
  // @@protoc_insertion_point(field_get:flwr.proto.Federation.runs)
  return _internal_runs(index);
}
inline ::flwr::proto::Run* Federation::_internal_add_runs() {
  return _impl_.runs_.Add();
}
inline ::flwr::proto::Run* Federation::add_runs() {
  ::flwr::proto::Run* _add = _internal_add_runs();
  // @@protoc_insertion_point(field_add:flwr.proto.Federation.runs)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::flwr::proto::Run >&
Federation::runs() const {
  // @@protoc_insertion_point(field_list:flwr.proto.Federation.runs)
  return _impl_.runs_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace flwr

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_flwr_2fproto_2ffederation_2eproto
