// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: flwr/proto/grpcadapter.proto

#include "flwr/proto/grpcadapter.pb.h"
#include "flwr/proto/grpcadapter.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace flwr {
namespace proto {

static const char* GrpcAdapter_method_names[] = {
  "/flwr.proto.GrpcAdapter/SendReceive",
};

std::unique_ptr< GrpcAdapter::Stub> GrpcAdapter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GrpcAdapter::Stub> stub(new GrpcAdapter::Stub(channel, options));
  return stub;
}

GrpcAdapter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendReceive_(GrpcAdapter_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GrpcAdapter::Stub::SendReceive(::grpc::ClientContext* context, const ::flwr::proto::MessageContainer& request, ::flwr::proto::MessageContainer* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::MessageContainer, ::flwr::proto::MessageContainer, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendReceive_, context, request, response);
}

void GrpcAdapter::Stub::async::SendReceive(::grpc::ClientContext* context, const ::flwr::proto::MessageContainer* request, ::flwr::proto::MessageContainer* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::MessageContainer, ::flwr::proto::MessageContainer, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendReceive_, context, request, response, std::move(f));
}

void GrpcAdapter::Stub::async::SendReceive(::grpc::ClientContext* context, const ::flwr::proto::MessageContainer* request, ::flwr::proto::MessageContainer* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendReceive_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::MessageContainer>* GrpcAdapter::Stub::PrepareAsyncSendReceiveRaw(::grpc::ClientContext* context, const ::flwr::proto::MessageContainer& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::MessageContainer, ::flwr::proto::MessageContainer, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendReceive_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::MessageContainer>* GrpcAdapter::Stub::AsyncSendReceiveRaw(::grpc::ClientContext* context, const ::flwr::proto::MessageContainer& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendReceiveRaw(context, request, cq);
  result->StartCall();
  return result;
}

GrpcAdapter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GrpcAdapter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GrpcAdapter::Service, ::flwr::proto::MessageContainer, ::flwr::proto::MessageContainer, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GrpcAdapter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::MessageContainer* req,
             ::flwr::proto::MessageContainer* resp) {
               return service->SendReceive(ctx, req, resp);
             }, this)));
}

GrpcAdapter::Service::~Service() {
}

::grpc::Status GrpcAdapter::Service::SendReceive(::grpc::ServerContext* context, const ::flwr::proto::MessageContainer* request, ::flwr::proto::MessageContainer* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace flwr
}  // namespace proto

