// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flwr/proto/heartbeat.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_flwr_2fproto_2fheartbeat_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_flwr_2fproto_2fheartbeat_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "flwr/proto/node.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_flwr_2fproto_2fheartbeat_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_flwr_2fproto_2fheartbeat_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_flwr_2fproto_2fheartbeat_2eproto;
namespace flwr {
namespace proto {
class SendAppHeartbeatRequest;
struct SendAppHeartbeatRequestDefaultTypeInternal;
extern SendAppHeartbeatRequestDefaultTypeInternal _SendAppHeartbeatRequest_default_instance_;
class SendAppHeartbeatResponse;
struct SendAppHeartbeatResponseDefaultTypeInternal;
extern SendAppHeartbeatResponseDefaultTypeInternal _SendAppHeartbeatResponse_default_instance_;
class SendNodeHeartbeatRequest;
struct SendNodeHeartbeatRequestDefaultTypeInternal;
extern SendNodeHeartbeatRequestDefaultTypeInternal _SendNodeHeartbeatRequest_default_instance_;
class SendNodeHeartbeatResponse;
struct SendNodeHeartbeatResponseDefaultTypeInternal;
extern SendNodeHeartbeatResponseDefaultTypeInternal _SendNodeHeartbeatResponse_default_instance_;
}  // namespace proto
}  // namespace flwr
PROTOBUF_NAMESPACE_OPEN
template<> ::flwr::proto::SendAppHeartbeatRequest* Arena::CreateMaybeMessage<::flwr::proto::SendAppHeartbeatRequest>(Arena*);
template<> ::flwr::proto::SendAppHeartbeatResponse* Arena::CreateMaybeMessage<::flwr::proto::SendAppHeartbeatResponse>(Arena*);
template<> ::flwr::proto::SendNodeHeartbeatRequest* Arena::CreateMaybeMessage<::flwr::proto::SendNodeHeartbeatRequest>(Arena*);
template<> ::flwr::proto::SendNodeHeartbeatResponse* Arena::CreateMaybeMessage<::flwr::proto::SendNodeHeartbeatResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace flwr {
namespace proto {

// ===================================================================

class SendNodeHeartbeatRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:flwr.proto.SendNodeHeartbeatRequest) */ {
 public:
  inline SendNodeHeartbeatRequest() : SendNodeHeartbeatRequest(nullptr) {}
  ~SendNodeHeartbeatRequest() override;
  explicit PROTOBUF_CONSTEXPR SendNodeHeartbeatRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SendNodeHeartbeatRequest(const SendNodeHeartbeatRequest& from);
  SendNodeHeartbeatRequest(SendNodeHeartbeatRequest&& from) noexcept
    : SendNodeHeartbeatRequest() {
    *this = ::std::move(from);
  }

  inline SendNodeHeartbeatRequest& operator=(const SendNodeHeartbeatRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendNodeHeartbeatRequest& operator=(SendNodeHeartbeatRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendNodeHeartbeatRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SendNodeHeartbeatRequest* internal_default_instance() {
    return reinterpret_cast<const SendNodeHeartbeatRequest*>(
               &_SendNodeHeartbeatRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SendNodeHeartbeatRequest& a, SendNodeHeartbeatRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SendNodeHeartbeatRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendNodeHeartbeatRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendNodeHeartbeatRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SendNodeHeartbeatRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SendNodeHeartbeatRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SendNodeHeartbeatRequest& from) {
    SendNodeHeartbeatRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendNodeHeartbeatRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "flwr.proto.SendNodeHeartbeatRequest";
  }
  protected:
  explicit SendNodeHeartbeatRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodeFieldNumber = 1,
    kHeartbeatIntervalFieldNumber = 2,
  };
  // .flwr.proto.Node node = 1;
  bool has_node() const;
  private:
  bool _internal_has_node() const;
  public:
  void clear_node();
  const ::flwr::proto::Node& node() const;
  PROTOBUF_NODISCARD ::flwr::proto::Node* release_node();
  ::flwr::proto::Node* mutable_node();
  void set_allocated_node(::flwr::proto::Node* node);
  private:
  const ::flwr::proto::Node& _internal_node() const;
  ::flwr::proto::Node* _internal_mutable_node();
  public:
  void unsafe_arena_set_allocated_node(
      ::flwr::proto::Node* node);
  ::flwr::proto::Node* unsafe_arena_release_node();

  // double heartbeat_interval = 2;
  void clear_heartbeat_interval();
  double heartbeat_interval() const;
  void set_heartbeat_interval(double value);
  private:
  double _internal_heartbeat_interval() const;
  void _internal_set_heartbeat_interval(double value);
  public:

  // @@protoc_insertion_point(class_scope:flwr.proto.SendNodeHeartbeatRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::flwr::proto::Node* node_;
    double heartbeat_interval_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_flwr_2fproto_2fheartbeat_2eproto;
};
// -------------------------------------------------------------------

class SendNodeHeartbeatResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:flwr.proto.SendNodeHeartbeatResponse) */ {
 public:
  inline SendNodeHeartbeatResponse() : SendNodeHeartbeatResponse(nullptr) {}
  ~SendNodeHeartbeatResponse() override;
  explicit PROTOBUF_CONSTEXPR SendNodeHeartbeatResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SendNodeHeartbeatResponse(const SendNodeHeartbeatResponse& from);
  SendNodeHeartbeatResponse(SendNodeHeartbeatResponse&& from) noexcept
    : SendNodeHeartbeatResponse() {
    *this = ::std::move(from);
  }

  inline SendNodeHeartbeatResponse& operator=(const SendNodeHeartbeatResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendNodeHeartbeatResponse& operator=(SendNodeHeartbeatResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendNodeHeartbeatResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SendNodeHeartbeatResponse* internal_default_instance() {
    return reinterpret_cast<const SendNodeHeartbeatResponse*>(
               &_SendNodeHeartbeatResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SendNodeHeartbeatResponse& a, SendNodeHeartbeatResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SendNodeHeartbeatResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendNodeHeartbeatResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendNodeHeartbeatResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SendNodeHeartbeatResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SendNodeHeartbeatResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SendNodeHeartbeatResponse& from) {
    SendNodeHeartbeatResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendNodeHeartbeatResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "flwr.proto.SendNodeHeartbeatResponse";
  }
  protected:
  explicit SendNodeHeartbeatResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:flwr.proto.SendNodeHeartbeatResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_flwr_2fproto_2fheartbeat_2eproto;
};
// -------------------------------------------------------------------

class SendAppHeartbeatRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:flwr.proto.SendAppHeartbeatRequest) */ {
 public:
  inline SendAppHeartbeatRequest() : SendAppHeartbeatRequest(nullptr) {}
  ~SendAppHeartbeatRequest() override;
  explicit PROTOBUF_CONSTEXPR SendAppHeartbeatRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SendAppHeartbeatRequest(const SendAppHeartbeatRequest& from);
  SendAppHeartbeatRequest(SendAppHeartbeatRequest&& from) noexcept
    : SendAppHeartbeatRequest() {
    *this = ::std::move(from);
  }

  inline SendAppHeartbeatRequest& operator=(const SendAppHeartbeatRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendAppHeartbeatRequest& operator=(SendAppHeartbeatRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendAppHeartbeatRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SendAppHeartbeatRequest* internal_default_instance() {
    return reinterpret_cast<const SendAppHeartbeatRequest*>(
               &_SendAppHeartbeatRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SendAppHeartbeatRequest& a, SendAppHeartbeatRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SendAppHeartbeatRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendAppHeartbeatRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendAppHeartbeatRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SendAppHeartbeatRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SendAppHeartbeatRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SendAppHeartbeatRequest& from) {
    SendAppHeartbeatRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendAppHeartbeatRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "flwr.proto.SendAppHeartbeatRequest";
  }
  protected:
  explicit SendAppHeartbeatRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTokenFieldNumber = 1,
  };
  // string token = 1;
  void clear_token();
  const std::string& token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_token();
  PROTOBUF_NODISCARD std::string* release_token();
  void set_allocated_token(std::string* token);
  private:
  const std::string& _internal_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token(const std::string& value);
  std::string* _internal_mutable_token();
  public:

  // @@protoc_insertion_point(class_scope:flwr.proto.SendAppHeartbeatRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr token_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_flwr_2fproto_2fheartbeat_2eproto;
};
// -------------------------------------------------------------------

class SendAppHeartbeatResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:flwr.proto.SendAppHeartbeatResponse) */ {
 public:
  inline SendAppHeartbeatResponse() : SendAppHeartbeatResponse(nullptr) {}
  ~SendAppHeartbeatResponse() override;
  explicit PROTOBUF_CONSTEXPR SendAppHeartbeatResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SendAppHeartbeatResponse(const SendAppHeartbeatResponse& from);
  SendAppHeartbeatResponse(SendAppHeartbeatResponse&& from) noexcept
    : SendAppHeartbeatResponse() {
    *this = ::std::move(from);
  }

  inline SendAppHeartbeatResponse& operator=(const SendAppHeartbeatResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendAppHeartbeatResponse& operator=(SendAppHeartbeatResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendAppHeartbeatResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SendAppHeartbeatResponse* internal_default_instance() {
    return reinterpret_cast<const SendAppHeartbeatResponse*>(
               &_SendAppHeartbeatResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SendAppHeartbeatResponse& a, SendAppHeartbeatResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SendAppHeartbeatResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendAppHeartbeatResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendAppHeartbeatResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SendAppHeartbeatResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SendAppHeartbeatResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SendAppHeartbeatResponse& from) {
    SendAppHeartbeatResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendAppHeartbeatResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "flwr.proto.SendAppHeartbeatResponse";
  }
  protected:
  explicit SendAppHeartbeatResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:flwr.proto.SendAppHeartbeatResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_flwr_2fproto_2fheartbeat_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SendNodeHeartbeatRequest

// .flwr.proto.Node node = 1;
inline bool SendNodeHeartbeatRequest::_internal_has_node() const {
  return this != internal_default_instance() && _impl_.node_ != nullptr;
}
inline bool SendNodeHeartbeatRequest::has_node() const {
  return _internal_has_node();
}
inline const ::flwr::proto::Node& SendNodeHeartbeatRequest::_internal_node() const {
  const ::flwr::proto::Node* p = _impl_.node_;
  return p != nullptr ? *p : reinterpret_cast<const ::flwr::proto::Node&>(
      ::flwr::proto::_Node_default_instance_);
}
inline const ::flwr::proto::Node& SendNodeHeartbeatRequest::node() const {
  // @@protoc_insertion_point(field_get:flwr.proto.SendNodeHeartbeatRequest.node)
  return _internal_node();
}
inline void SendNodeHeartbeatRequest::unsafe_arena_set_allocated_node(
    ::flwr::proto::Node* node) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.node_);
  }
  _impl_.node_ = node;
  if (node) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:flwr.proto.SendNodeHeartbeatRequest.node)
}
inline ::flwr::proto::Node* SendNodeHeartbeatRequest::release_node() {
  
  ::flwr::proto::Node* temp = _impl_.node_;
  _impl_.node_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::flwr::proto::Node* SendNodeHeartbeatRequest::unsafe_arena_release_node() {
  // @@protoc_insertion_point(field_release:flwr.proto.SendNodeHeartbeatRequest.node)
  
  ::flwr::proto::Node* temp = _impl_.node_;
  _impl_.node_ = nullptr;
  return temp;
}
inline ::flwr::proto::Node* SendNodeHeartbeatRequest::_internal_mutable_node() {
  
  if (_impl_.node_ == nullptr) {
    auto* p = CreateMaybeMessage<::flwr::proto::Node>(GetArenaForAllocation());
    _impl_.node_ = p;
  }
  return _impl_.node_;
}
inline ::flwr::proto::Node* SendNodeHeartbeatRequest::mutable_node() {
  ::flwr::proto::Node* _msg = _internal_mutable_node();
  // @@protoc_insertion_point(field_mutable:flwr.proto.SendNodeHeartbeatRequest.node)
  return _msg;
}
inline void SendNodeHeartbeatRequest::set_allocated_node(::flwr::proto::Node* node) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.node_);
  }
  if (node) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(node));
    if (message_arena != submessage_arena) {
      node = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, node, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.node_ = node;
  // @@protoc_insertion_point(field_set_allocated:flwr.proto.SendNodeHeartbeatRequest.node)
}

// double heartbeat_interval = 2;
inline void SendNodeHeartbeatRequest::clear_heartbeat_interval() {
  _impl_.heartbeat_interval_ = 0;
}
inline double SendNodeHeartbeatRequest::_internal_heartbeat_interval() const {
  return _impl_.heartbeat_interval_;
}
inline double SendNodeHeartbeatRequest::heartbeat_interval() const {
  // @@protoc_insertion_point(field_get:flwr.proto.SendNodeHeartbeatRequest.heartbeat_interval)
  return _internal_heartbeat_interval();
}
inline void SendNodeHeartbeatRequest::_internal_set_heartbeat_interval(double value) {
  
  _impl_.heartbeat_interval_ = value;
}
inline void SendNodeHeartbeatRequest::set_heartbeat_interval(double value) {
  _internal_set_heartbeat_interval(value);
  // @@protoc_insertion_point(field_set:flwr.proto.SendNodeHeartbeatRequest.heartbeat_interval)
}

// -------------------------------------------------------------------

// SendNodeHeartbeatResponse

// bool success = 1;
inline void SendNodeHeartbeatResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool SendNodeHeartbeatResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool SendNodeHeartbeatResponse::success() const {
  // @@protoc_insertion_point(field_get:flwr.proto.SendNodeHeartbeatResponse.success)
  return _internal_success();
}
inline void SendNodeHeartbeatResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void SendNodeHeartbeatResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:flwr.proto.SendNodeHeartbeatResponse.success)
}

// -------------------------------------------------------------------

// SendAppHeartbeatRequest

// string token = 1;
inline void SendAppHeartbeatRequest::clear_token() {
  _impl_.token_.ClearToEmpty();
}
inline const std::string& SendAppHeartbeatRequest::token() const {
  // @@protoc_insertion_point(field_get:flwr.proto.SendAppHeartbeatRequest.token)
  return _internal_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SendAppHeartbeatRequest::set_token(ArgT0&& arg0, ArgT... args) {
 
 _impl_.token_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:flwr.proto.SendAppHeartbeatRequest.token)
}
inline std::string* SendAppHeartbeatRequest::mutable_token() {
  std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:flwr.proto.SendAppHeartbeatRequest.token)
  return _s;
}
inline const std::string& SendAppHeartbeatRequest::_internal_token() const {
  return _impl_.token_.Get();
}
inline void SendAppHeartbeatRequest::_internal_set_token(const std::string& value) {
  
  _impl_.token_.Set(value, GetArenaForAllocation());
}
inline std::string* SendAppHeartbeatRequest::_internal_mutable_token() {
  
  return _impl_.token_.Mutable(GetArenaForAllocation());
}
inline std::string* SendAppHeartbeatRequest::release_token() {
  // @@protoc_insertion_point(field_release:flwr.proto.SendAppHeartbeatRequest.token)
  return _impl_.token_.Release();
}
inline void SendAppHeartbeatRequest::set_allocated_token(std::string* token) {
  if (token != nullptr) {
    
  } else {
    
  }
  _impl_.token_.SetAllocated(token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.token_.IsDefault()) {
    _impl_.token_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:flwr.proto.SendAppHeartbeatRequest.token)
}

// -------------------------------------------------------------------

// SendAppHeartbeatResponse

// bool success = 1;
inline void SendAppHeartbeatResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool SendAppHeartbeatResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool SendAppHeartbeatResponse::success() const {
  // @@protoc_insertion_point(field_get:flwr.proto.SendAppHeartbeatResponse.success)
  return _internal_success();
}
inline void SendAppHeartbeatResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void SendAppHeartbeatResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:flwr.proto.SendAppHeartbeatResponse.success)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace flwr

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_flwr_2fproto_2fheartbeat_2eproto
