// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flwr/proto/log.proto

#include "flwr/proto/log.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace flwr {
namespace proto {
PROTOBUF_CONSTEXPR PushLogsRequest::PushLogsRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.logs_)*/{}
  , /*decltype(_impl_.node_)*/nullptr
  , /*decltype(_impl_.run_id_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PushLogsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PushLogsRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PushLogsRequestDefaultTypeInternal() {}
  union {
    PushLogsRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PushLogsRequestDefaultTypeInternal _PushLogsRequest_default_instance_;
PROTOBUF_CONSTEXPR PushLogsResponse::PushLogsResponse(
    ::_pbi::ConstantInitialized) {}
struct PushLogsResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PushLogsResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PushLogsResponseDefaultTypeInternal() {}
  union {
    PushLogsResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PushLogsResponseDefaultTypeInternal _PushLogsResponse_default_instance_;
}  // namespace proto
}  // namespace flwr
static ::_pb::Metadata file_level_metadata_flwr_2fproto_2flog_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_flwr_2fproto_2flog_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_flwr_2fproto_2flog_2eproto = nullptr;

const uint32_t TableStruct_flwr_2fproto_2flog_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::PushLogsRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::PushLogsRequest, _impl_.node_),
  PROTOBUF_FIELD_OFFSET(::flwr::proto::PushLogsRequest, _impl_.run_id_),
  PROTOBUF_FIELD_OFFSET(::flwr::proto::PushLogsRequest, _impl_.logs_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::PushLogsResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::flwr::proto::PushLogsRequest)},
  { 9, -1, -1, sizeof(::flwr::proto::PushLogsResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::flwr::proto::_PushLogsRequest_default_instance_._instance,
  &::flwr::proto::_PushLogsResponse_default_instance_._instance,
};

const char descriptor_table_protodef_flwr_2fproto_2flog_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024flwr/proto/log.proto\022\nflwr.proto\032\025flwr"
  "/proto/node.proto\"O\n\017PushLogsRequest\022\036\n\004"
  "node\030\001 \001(\0132\020.flwr.proto.Node\022\016\n\006run_id\030\002"
  " \001(\004\022\014\n\004logs\030\003 \003(\t\"\022\n\020PushLogsResponseb\006"
  "proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_flwr_2fproto_2flog_2eproto_deps[1] = {
  &::descriptor_table_flwr_2fproto_2fnode_2eproto,
};
static ::_pbi::once_flag descriptor_table_flwr_2fproto_2flog_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_flwr_2fproto_2flog_2eproto = {
    false, false, 166, descriptor_table_protodef_flwr_2fproto_2flog_2eproto,
    "flwr/proto/log.proto",
    &descriptor_table_flwr_2fproto_2flog_2eproto_once, descriptor_table_flwr_2fproto_2flog_2eproto_deps, 1, 2,
    schemas, file_default_instances, TableStruct_flwr_2fproto_2flog_2eproto::offsets,
    file_level_metadata_flwr_2fproto_2flog_2eproto, file_level_enum_descriptors_flwr_2fproto_2flog_2eproto,
    file_level_service_descriptors_flwr_2fproto_2flog_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_flwr_2fproto_2flog_2eproto_getter() {
  return &descriptor_table_flwr_2fproto_2flog_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_flwr_2fproto_2flog_2eproto(&descriptor_table_flwr_2fproto_2flog_2eproto);
namespace flwr {
namespace proto {

// ===================================================================

class PushLogsRequest::_Internal {
 public:
  static const ::flwr::proto::Node& node(const PushLogsRequest* msg);
};

const ::flwr::proto::Node&
PushLogsRequest::_Internal::node(const PushLogsRequest* msg) {
  return *msg->_impl_.node_;
}
void PushLogsRequest::clear_node() {
  if (GetArenaForAllocation() == nullptr && _impl_.node_ != nullptr) {
    delete _impl_.node_;
  }
  _impl_.node_ = nullptr;
}
PushLogsRequest::PushLogsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:flwr.proto.PushLogsRequest)
}
PushLogsRequest::PushLogsRequest(const PushLogsRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PushLogsRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.logs_){from._impl_.logs_}
    , decltype(_impl_.node_){nullptr}
    , decltype(_impl_.run_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_node()) {
    _this->_impl_.node_ = new ::flwr::proto::Node(*from._impl_.node_);
  }
  _this->_impl_.run_id_ = from._impl_.run_id_;
  // @@protoc_insertion_point(copy_constructor:flwr.proto.PushLogsRequest)
}

inline void PushLogsRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.logs_){arena}
    , decltype(_impl_.node_){nullptr}
    , decltype(_impl_.run_id_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PushLogsRequest::~PushLogsRequest() {
  // @@protoc_insertion_point(destructor:flwr.proto.PushLogsRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PushLogsRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.logs_.~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.node_;
}

void PushLogsRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PushLogsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:flwr.proto.PushLogsRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.logs_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.node_ != nullptr) {
    delete _impl_.node_;
  }
  _impl_.node_ = nullptr;
  _impl_.run_id_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PushLogsRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .flwr.proto.Node node = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_node(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 run_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.run_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated string logs = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_logs();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "flwr.proto.PushLogsRequest.logs"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PushLogsRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:flwr.proto.PushLogsRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .flwr.proto.Node node = 1;
  if (this->_internal_has_node()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::node(this),
        _Internal::node(this).GetCachedSize(), target, stream);
  }

  // uint64 run_id = 2;
  if (this->_internal_run_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_run_id(), target);
  }

  // repeated string logs = 3;
  for (int i = 0, n = this->_internal_logs_size(); i < n; i++) {
    const auto& s = this->_internal_logs(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "flwr.proto.PushLogsRequest.logs");
    target = stream->WriteString(3, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:flwr.proto.PushLogsRequest)
  return target;
}

size_t PushLogsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:flwr.proto.PushLogsRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string logs = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.logs_.size());
  for (int i = 0, n = _impl_.logs_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.logs_.Get(i));
  }

  // .flwr.proto.Node node = 1;
  if (this->_internal_has_node()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.node_);
  }

  // uint64 run_id = 2;
  if (this->_internal_run_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_run_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PushLogsRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PushLogsRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PushLogsRequest::GetClassData() const { return &_class_data_; }


void PushLogsRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PushLogsRequest*>(&to_msg);
  auto& from = static_cast<const PushLogsRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:flwr.proto.PushLogsRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.logs_.MergeFrom(from._impl_.logs_);
  if (from._internal_has_node()) {
    _this->_internal_mutable_node()->::flwr::proto::Node::MergeFrom(
        from._internal_node());
  }
  if (from._internal_run_id() != 0) {
    _this->_internal_set_run_id(from._internal_run_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PushLogsRequest::CopyFrom(const PushLogsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flwr.proto.PushLogsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PushLogsRequest::IsInitialized() const {
  return true;
}

void PushLogsRequest::InternalSwap(PushLogsRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.logs_.InternalSwap(&other->_impl_.logs_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PushLogsRequest, _impl_.run_id_)
      + sizeof(PushLogsRequest::_impl_.run_id_)
      - PROTOBUF_FIELD_OFFSET(PushLogsRequest, _impl_.node_)>(
          reinterpret_cast<char*>(&_impl_.node_),
          reinterpret_cast<char*>(&other->_impl_.node_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PushLogsRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_flwr_2fproto_2flog_2eproto_getter, &descriptor_table_flwr_2fproto_2flog_2eproto_once,
      file_level_metadata_flwr_2fproto_2flog_2eproto[0]);
}

// ===================================================================

class PushLogsResponse::_Internal {
 public:
};

PushLogsResponse::PushLogsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:flwr.proto.PushLogsResponse)
}
PushLogsResponse::PushLogsResponse(const PushLogsResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  PushLogsResponse* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:flwr.proto.PushLogsResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PushLogsResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PushLogsResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata PushLogsResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_flwr_2fproto_2flog_2eproto_getter, &descriptor_table_flwr_2fproto_2flog_2eproto_once,
      file_level_metadata_flwr_2fproto_2flog_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace flwr
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::flwr::proto::PushLogsRequest*
Arena::CreateMaybeMessage< ::flwr::proto::PushLogsRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::flwr::proto::PushLogsRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::flwr::proto::PushLogsResponse*
Arena::CreateMaybeMessage< ::flwr::proto::PushLogsResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::flwr::proto::PushLogsResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
