// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flwr/proto/log.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_flwr_2fproto_2flog_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_flwr_2fproto_2flog_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "flwr/proto/node.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_flwr_2fproto_2flog_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_flwr_2fproto_2flog_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_flwr_2fproto_2flog_2eproto;
namespace flwr {
namespace proto {
class PushLogsRequest;
struct PushLogsRequestDefaultTypeInternal;
extern PushLogsRequestDefaultTypeInternal _PushLogsRequest_default_instance_;
class PushLogsResponse;
struct PushLogsResponseDefaultTypeInternal;
extern PushLogsResponseDefaultTypeInternal _PushLogsResponse_default_instance_;
}  // namespace proto
}  // namespace flwr
PROTOBUF_NAMESPACE_OPEN
template<> ::flwr::proto::PushLogsRequest* Arena::CreateMaybeMessage<::flwr::proto::PushLogsRequest>(Arena*);
template<> ::flwr::proto::PushLogsResponse* Arena::CreateMaybeMessage<::flwr::proto::PushLogsResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace flwr {
namespace proto {

// ===================================================================

class PushLogsRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:flwr.proto.PushLogsRequest) */ {
 public:
  inline PushLogsRequest() : PushLogsRequest(nullptr) {}
  ~PushLogsRequest() override;
  explicit PROTOBUF_CONSTEXPR PushLogsRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PushLogsRequest(const PushLogsRequest& from);
  PushLogsRequest(PushLogsRequest&& from) noexcept
    : PushLogsRequest() {
    *this = ::std::move(from);
  }

  inline PushLogsRequest& operator=(const PushLogsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PushLogsRequest& operator=(PushLogsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PushLogsRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const PushLogsRequest* internal_default_instance() {
    return reinterpret_cast<const PushLogsRequest*>(
               &_PushLogsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PushLogsRequest& a, PushLogsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PushLogsRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PushLogsRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PushLogsRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PushLogsRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PushLogsRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PushLogsRequest& from) {
    PushLogsRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PushLogsRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "flwr.proto.PushLogsRequest";
  }
  protected:
  explicit PushLogsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLogsFieldNumber = 3,
    kNodeFieldNumber = 1,
    kRunIdFieldNumber = 2,
  };
  // repeated string logs = 3;
  int logs_size() const;
  private:
  int _internal_logs_size() const;
  public:
  void clear_logs();
  const std::string& logs(int index) const;
  std::string* mutable_logs(int index);
  void set_logs(int index, const std::string& value);
  void set_logs(int index, std::string&& value);
  void set_logs(int index, const char* value);
  void set_logs(int index, const char* value, size_t size);
  std::string* add_logs();
  void add_logs(const std::string& value);
  void add_logs(std::string&& value);
  void add_logs(const char* value);
  void add_logs(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& logs() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_logs();
  private:
  const std::string& _internal_logs(int index) const;
  std::string* _internal_add_logs();
  public:

  // .flwr.proto.Node node = 1;
  bool has_node() const;
  private:
  bool _internal_has_node() const;
  public:
  void clear_node();
  const ::flwr::proto::Node& node() const;
  PROTOBUF_NODISCARD ::flwr::proto::Node* release_node();
  ::flwr::proto::Node* mutable_node();
  void set_allocated_node(::flwr::proto::Node* node);
  private:
  const ::flwr::proto::Node& _internal_node() const;
  ::flwr::proto::Node* _internal_mutable_node();
  public:
  void unsafe_arena_set_allocated_node(
      ::flwr::proto::Node* node);
  ::flwr::proto::Node* unsafe_arena_release_node();

  // uint64 run_id = 2;
  void clear_run_id();
  uint64_t run_id() const;
  void set_run_id(uint64_t value);
  private:
  uint64_t _internal_run_id() const;
  void _internal_set_run_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:flwr.proto.PushLogsRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> logs_;
    ::flwr::proto::Node* node_;
    uint64_t run_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_flwr_2fproto_2flog_2eproto;
};
// -------------------------------------------------------------------

class PushLogsResponse final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:flwr.proto.PushLogsResponse) */ {
 public:
  inline PushLogsResponse() : PushLogsResponse(nullptr) {}
  explicit PROTOBUF_CONSTEXPR PushLogsResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PushLogsResponse(const PushLogsResponse& from);
  PushLogsResponse(PushLogsResponse&& from) noexcept
    : PushLogsResponse() {
    *this = ::std::move(from);
  }

  inline PushLogsResponse& operator=(const PushLogsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PushLogsResponse& operator=(PushLogsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PushLogsResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const PushLogsResponse* internal_default_instance() {
    return reinterpret_cast<const PushLogsResponse*>(
               &_PushLogsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PushLogsResponse& a, PushLogsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PushLogsResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PushLogsResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PushLogsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PushLogsResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const PushLogsResponse& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const PushLogsResponse& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "flwr.proto.PushLogsResponse";
  }
  protected:
  explicit PushLogsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:flwr.proto.PushLogsResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_flwr_2fproto_2flog_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PushLogsRequest

// .flwr.proto.Node node = 1;
inline bool PushLogsRequest::_internal_has_node() const {
  return this != internal_default_instance() && _impl_.node_ != nullptr;
}
inline bool PushLogsRequest::has_node() const {
  return _internal_has_node();
}
inline const ::flwr::proto::Node& PushLogsRequest::_internal_node() const {
  const ::flwr::proto::Node* p = _impl_.node_;
  return p != nullptr ? *p : reinterpret_cast<const ::flwr::proto::Node&>(
      ::flwr::proto::_Node_default_instance_);
}
inline const ::flwr::proto::Node& PushLogsRequest::node() const {
  // @@protoc_insertion_point(field_get:flwr.proto.PushLogsRequest.node)
  return _internal_node();
}
inline void PushLogsRequest::unsafe_arena_set_allocated_node(
    ::flwr::proto::Node* node) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.node_);
  }
  _impl_.node_ = node;
  if (node) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:flwr.proto.PushLogsRequest.node)
}
inline ::flwr::proto::Node* PushLogsRequest::release_node() {
  
  ::flwr::proto::Node* temp = _impl_.node_;
  _impl_.node_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::flwr::proto::Node* PushLogsRequest::unsafe_arena_release_node() {
  // @@protoc_insertion_point(field_release:flwr.proto.PushLogsRequest.node)
  
  ::flwr::proto::Node* temp = _impl_.node_;
  _impl_.node_ = nullptr;
  return temp;
}
inline ::flwr::proto::Node* PushLogsRequest::_internal_mutable_node() {
  
  if (_impl_.node_ == nullptr) {
    auto* p = CreateMaybeMessage<::flwr::proto::Node>(GetArenaForAllocation());
    _impl_.node_ = p;
  }
  return _impl_.node_;
}
inline ::flwr::proto::Node* PushLogsRequest::mutable_node() {
  ::flwr::proto::Node* _msg = _internal_mutable_node();
  // @@protoc_insertion_point(field_mutable:flwr.proto.PushLogsRequest.node)
  return _msg;
}
inline void PushLogsRequest::set_allocated_node(::flwr::proto::Node* node) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.node_);
  }
  if (node) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(node));
    if (message_arena != submessage_arena) {
      node = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, node, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.node_ = node;
  // @@protoc_insertion_point(field_set_allocated:flwr.proto.PushLogsRequest.node)
}

// uint64 run_id = 2;
inline void PushLogsRequest::clear_run_id() {
  _impl_.run_id_ = uint64_t{0u};
}
inline uint64_t PushLogsRequest::_internal_run_id() const {
  return _impl_.run_id_;
}
inline uint64_t PushLogsRequest::run_id() const {
  // @@protoc_insertion_point(field_get:flwr.proto.PushLogsRequest.run_id)
  return _internal_run_id();
}
inline void PushLogsRequest::_internal_set_run_id(uint64_t value) {
  
  _impl_.run_id_ = value;
}
inline void PushLogsRequest::set_run_id(uint64_t value) {
  _internal_set_run_id(value);
  // @@protoc_insertion_point(field_set:flwr.proto.PushLogsRequest.run_id)
}

// repeated string logs = 3;
inline int PushLogsRequest::_internal_logs_size() const {
  return _impl_.logs_.size();
}
inline int PushLogsRequest::logs_size() const {
  return _internal_logs_size();
}
inline void PushLogsRequest::clear_logs() {
  _impl_.logs_.Clear();
}
inline std::string* PushLogsRequest::add_logs() {
  std::string* _s = _internal_add_logs();
  // @@protoc_insertion_point(field_add_mutable:flwr.proto.PushLogsRequest.logs)
  return _s;
}
inline const std::string& PushLogsRequest::_internal_logs(int index) const {
  return _impl_.logs_.Get(index);
}
inline const std::string& PushLogsRequest::logs(int index) const {
  // @@protoc_insertion_point(field_get:flwr.proto.PushLogsRequest.logs)
  return _internal_logs(index);
}
inline std::string* PushLogsRequest::mutable_logs(int index) {
  // @@protoc_insertion_point(field_mutable:flwr.proto.PushLogsRequest.logs)
  return _impl_.logs_.Mutable(index);
}
inline void PushLogsRequest::set_logs(int index, const std::string& value) {
  _impl_.logs_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:flwr.proto.PushLogsRequest.logs)
}
inline void PushLogsRequest::set_logs(int index, std::string&& value) {
  _impl_.logs_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:flwr.proto.PushLogsRequest.logs)
}
inline void PushLogsRequest::set_logs(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.logs_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:flwr.proto.PushLogsRequest.logs)
}
inline void PushLogsRequest::set_logs(int index, const char* value, size_t size) {
  _impl_.logs_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:flwr.proto.PushLogsRequest.logs)
}
inline std::string* PushLogsRequest::_internal_add_logs() {
  return _impl_.logs_.Add();
}
inline void PushLogsRequest::add_logs(const std::string& value) {
  _impl_.logs_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:flwr.proto.PushLogsRequest.logs)
}
inline void PushLogsRequest::add_logs(std::string&& value) {
  _impl_.logs_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:flwr.proto.PushLogsRequest.logs)
}
inline void PushLogsRequest::add_logs(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.logs_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:flwr.proto.PushLogsRequest.logs)
}
inline void PushLogsRequest::add_logs(const char* value, size_t size) {
  _impl_.logs_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:flwr.proto.PushLogsRequest.logs)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
PushLogsRequest::logs() const {
  // @@protoc_insertion_point(field_list:flwr.proto.PushLogsRequest.logs)
  return _impl_.logs_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
PushLogsRequest::mutable_logs() {
  // @@protoc_insertion_point(field_mutable_list:flwr.proto.PushLogsRequest.logs)
  return &_impl_.logs_;
}

// -------------------------------------------------------------------

// PushLogsResponse

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace flwr

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_flwr_2fproto_2flog_2eproto
