// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flwr/proto/serverappio.proto

#include "flwr/proto/serverappio.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace flwr {
namespace proto {
PROTOBUF_CONSTEXPR GetNodesRequest::GetNodesRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.run_id_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetNodesRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetNodesRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetNodesRequestDefaultTypeInternal() {}
  union {
    GetNodesRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetNodesRequestDefaultTypeInternal _GetNodesRequest_default_instance_;
PROTOBUF_CONSTEXPR GetNodesResponse::GetNodesResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.nodes_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetNodesResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetNodesResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetNodesResponseDefaultTypeInternal() {}
  union {
    GetNodesResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetNodesResponseDefaultTypeInternal _GetNodesResponse_default_instance_;
}  // namespace proto
}  // namespace flwr
static ::_pb::Metadata file_level_metadata_flwr_2fproto_2fserverappio_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_flwr_2fproto_2fserverappio_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_flwr_2fproto_2fserverappio_2eproto = nullptr;

const uint32_t TableStruct_flwr_2fproto_2fserverappio_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::GetNodesRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::GetNodesRequest, _impl_.run_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::GetNodesResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::flwr::proto::GetNodesResponse, _impl_.nodes_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::flwr::proto::GetNodesRequest)},
  { 7, -1, -1, sizeof(::flwr::proto::GetNodesResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::flwr::proto::_GetNodesRequest_default_instance_._instance,
  &::flwr::proto::_GetNodesResponse_default_instance_._instance,
};

const char descriptor_table_protodef_flwr_2fproto_2fserverappio_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\034flwr/proto/serverappio.proto\022\nflwr.pro"
  "to\032\032flwr/proto/heartbeat.proto\032\024flwr/pro"
  "to/log.proto\032\025flwr/proto/node.proto\032\030flw"
  "r/proto/message.proto\032\024flwr/proto/run.pr"
  "oto\032\024flwr/proto/fab.proto\032\026flwr/proto/ap"
  "pio.proto\"!\n\017GetNodesRequest\022\016\n\006run_id\030\001"
  " \001(\004\"3\n\020GetNodesResponse\022\037\n\005nodes\030\001 \003(\0132"
  "\020.flwr.proto.Node2\351\n\n\013ServerAppIo\022_\n\020Lis"
  "tAppsToLaunch\022#.flwr.proto.ListAppsToLau"
  "nchRequest\032$.flwr.proto.ListAppsToLaunch"
  "Response\"\000\022S\n\014RequestToken\022\037.flwr.proto."
  "RequestTokenRequest\032 .flwr.proto.Request"
  "TokenResponse\"\000\022G\n\010GetNodes\022\033.flwr.proto"
  ".GetNodesRequest\032\034.flwr.proto.GetNodesRe"
  "sponse\"\000\022Y\n\014PushMessages\022\".flwr.proto.Pu"
  "shAppMessagesRequest\032#.flwr.proto.PushAp"
  "pMessagesResponse\"\000\022Y\n\014PullMessages\022\".fl"
  "wr.proto.PullAppMessagesRequest\032#.flwr.p"
  "roto.PullAppMessagesResponse\"\000\022A\n\006GetRun"
  "\022\031.flwr.proto.GetRunRequest\032\032.flwr.proto"
  ".GetRunResponse\"\000\022A\n\006GetFab\022\031.flwr.proto"
  ".GetFabRequest\032\032.flwr.proto.GetFabRespon"
  "se\"\000\022V\n\rPullAppInputs\022 .flwr.proto.PullA"
  "ppInputsRequest\032!.flwr.proto.PullAppInpu"
  "tsResponse\"\000\022Y\n\016PushAppOutputs\022!.flwr.pr"
  "oto.PushAppOutputsRequest\032\".flwr.proto.P"
  "ushAppOutputsResponse\"\000\022\\\n\017UpdateRunStat"
  "us\022\".flwr.proto.UpdateRunStatusRequest\032#"
  ".flwr.proto.UpdateRunStatusResponse\"\000\022S\n"
  "\014GetRunStatus\022\037.flwr.proto.GetRunStatusR"
  "equest\032 .flwr.proto.GetRunStatusResponse"
  "\"\000\022G\n\010PushLogs\022\033.flwr.proto.PushLogsRequ"
  "est\032\034.flwr.proto.PushLogsResponse\"\000\022_\n\020S"
  "endAppHeartbeat\022#.flwr.proto.SendAppHear"
  "tbeatRequest\032$.flwr.proto.SendAppHeartbe"
  "atResponse\"\000\022M\n\nPushObject\022\035.flwr.proto."
  "PushObjectRequest\032\036.flwr.proto.PushObjec"
  "tResponse\"\000\022M\n\nPullObject\022\035.flwr.proto.P"
  "ullObjectRequest\032\036.flwr.proto.PullObject"
  "Response\"\000\022q\n\026ConfirmMessageReceived\022).f"
  "lwr.proto.ConfirmMessageReceivedRequest\032"
  "*.flwr.proto.ConfirmMessageReceivedRespo"
  "nse\"\000b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_flwr_2fproto_2fserverappio_2eproto_deps[7] = {
  &::descriptor_table_flwr_2fproto_2fappio_2eproto,
  &::descriptor_table_flwr_2fproto_2ffab_2eproto,
  &::descriptor_table_flwr_2fproto_2fheartbeat_2eproto,
  &::descriptor_table_flwr_2fproto_2flog_2eproto,
  &::descriptor_table_flwr_2fproto_2fmessage_2eproto,
  &::descriptor_table_flwr_2fproto_2fnode_2eproto,
  &::descriptor_table_flwr_2fproto_2frun_2eproto,
};
static ::_pbi::once_flag descriptor_table_flwr_2fproto_2fserverappio_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_flwr_2fproto_2fserverappio_2eproto = {
    false, false, 1693, descriptor_table_protodef_flwr_2fproto_2fserverappio_2eproto,
    "flwr/proto/serverappio.proto",
    &descriptor_table_flwr_2fproto_2fserverappio_2eproto_once, descriptor_table_flwr_2fproto_2fserverappio_2eproto_deps, 7, 2,
    schemas, file_default_instances, TableStruct_flwr_2fproto_2fserverappio_2eproto::offsets,
    file_level_metadata_flwr_2fproto_2fserverappio_2eproto, file_level_enum_descriptors_flwr_2fproto_2fserverappio_2eproto,
    file_level_service_descriptors_flwr_2fproto_2fserverappio_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_flwr_2fproto_2fserverappio_2eproto_getter() {
  return &descriptor_table_flwr_2fproto_2fserverappio_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_flwr_2fproto_2fserverappio_2eproto(&descriptor_table_flwr_2fproto_2fserverappio_2eproto);
namespace flwr {
namespace proto {

// ===================================================================

class GetNodesRequest::_Internal {
 public:
};

GetNodesRequest::GetNodesRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:flwr.proto.GetNodesRequest)
}
GetNodesRequest::GetNodesRequest(const GetNodesRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetNodesRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.run_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.run_id_ = from._impl_.run_id_;
  // @@protoc_insertion_point(copy_constructor:flwr.proto.GetNodesRequest)
}

inline void GetNodesRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.run_id_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetNodesRequest::~GetNodesRequest() {
  // @@protoc_insertion_point(destructor:flwr.proto.GetNodesRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetNodesRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GetNodesRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetNodesRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:flwr.proto.GetNodesRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.run_id_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetNodesRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 run_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.run_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetNodesRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:flwr.proto.GetNodesRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 run_id = 1;
  if (this->_internal_run_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_run_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:flwr.proto.GetNodesRequest)
  return target;
}

size_t GetNodesRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:flwr.proto.GetNodesRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 run_id = 1;
  if (this->_internal_run_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_run_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetNodesRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetNodesRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetNodesRequest::GetClassData() const { return &_class_data_; }


void GetNodesRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetNodesRequest*>(&to_msg);
  auto& from = static_cast<const GetNodesRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:flwr.proto.GetNodesRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_run_id() != 0) {
    _this->_internal_set_run_id(from._internal_run_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetNodesRequest::CopyFrom(const GetNodesRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flwr.proto.GetNodesRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetNodesRequest::IsInitialized() const {
  return true;
}

void GetNodesRequest::InternalSwap(GetNodesRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.run_id_, other->_impl_.run_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetNodesRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_flwr_2fproto_2fserverappio_2eproto_getter, &descriptor_table_flwr_2fproto_2fserverappio_2eproto_once,
      file_level_metadata_flwr_2fproto_2fserverappio_2eproto[0]);
}

// ===================================================================

class GetNodesResponse::_Internal {
 public:
};

void GetNodesResponse::clear_nodes() {
  _impl_.nodes_.Clear();
}
GetNodesResponse::GetNodesResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:flwr.proto.GetNodesResponse)
}
GetNodesResponse::GetNodesResponse(const GetNodesResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetNodesResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.nodes_){from._impl_.nodes_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:flwr.proto.GetNodesResponse)
}

inline void GetNodesResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.nodes_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetNodesResponse::~GetNodesResponse() {
  // @@protoc_insertion_point(destructor:flwr.proto.GetNodesResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetNodesResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.nodes_.~RepeatedPtrField();
}

void GetNodesResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetNodesResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:flwr.proto.GetNodesResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.nodes_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetNodesResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .flwr.proto.Node nodes = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_nodes(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetNodesResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:flwr.proto.GetNodesResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .flwr.proto.Node nodes = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_nodes_size()); i < n; i++) {
    const auto& repfield = this->_internal_nodes(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:flwr.proto.GetNodesResponse)
  return target;
}

size_t GetNodesResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:flwr.proto.GetNodesResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .flwr.proto.Node nodes = 1;
  total_size += 1UL * this->_internal_nodes_size();
  for (const auto& msg : this->_impl_.nodes_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetNodesResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetNodesResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetNodesResponse::GetClassData() const { return &_class_data_; }


void GetNodesResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetNodesResponse*>(&to_msg);
  auto& from = static_cast<const GetNodesResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:flwr.proto.GetNodesResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.nodes_.MergeFrom(from._impl_.nodes_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetNodesResponse::CopyFrom(const GetNodesResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flwr.proto.GetNodesResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetNodesResponse::IsInitialized() const {
  return true;
}

void GetNodesResponse::InternalSwap(GetNodesResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.nodes_.InternalSwap(&other->_impl_.nodes_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetNodesResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_flwr_2fproto_2fserverappio_2eproto_getter, &descriptor_table_flwr_2fproto_2fserverappio_2eproto_once,
      file_level_metadata_flwr_2fproto_2fserverappio_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace flwr
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::flwr::proto::GetNodesRequest*
Arena::CreateMaybeMessage< ::flwr::proto::GetNodesRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::flwr::proto::GetNodesRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::flwr::proto::GetNodesResponse*
Arena::CreateMaybeMessage< ::flwr::proto::GetNodesResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::flwr::proto::GetNodesResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
