// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: flwr/proto/serverappio.proto

#include "flwr/proto/serverappio.pb.h"
#include "flwr/proto/serverappio.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace flwr {
namespace proto {

static const char* ServerAppIo_method_names[] = {
  "/flwr.proto.ServerAppIo/ListAppsToLaunch",
  "/flwr.proto.ServerAppIo/RequestToken",
  "/flwr.proto.ServerAppIo/GetNodes",
  "/flwr.proto.ServerAppIo/PushMessages",
  "/flwr.proto.ServerAppIo/PullMessages",
  "/flwr.proto.ServerAppIo/GetRun",
  "/flwr.proto.ServerAppIo/GetFab",
  "/flwr.proto.ServerAppIo/PullAppInputs",
  "/flwr.proto.ServerAppIo/PushAppOutputs",
  "/flwr.proto.ServerAppIo/UpdateRunStatus",
  "/flwr.proto.ServerAppIo/GetRunStatus",
  "/flwr.proto.ServerAppIo/PushLogs",
  "/flwr.proto.ServerAppIo/SendAppHeartbeat",
  "/flwr.proto.ServerAppIo/PushObject",
  "/flwr.proto.ServerAppIo/PullObject",
  "/flwr.proto.ServerAppIo/ConfirmMessageReceived",
};

std::unique_ptr< ServerAppIo::Stub> ServerAppIo::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ServerAppIo::Stub> stub(new ServerAppIo::Stub(channel, options));
  return stub;
}

ServerAppIo::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ListAppsToLaunch_(ServerAppIo_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RequestToken_(ServerAppIo_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetNodes_(ServerAppIo_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PushMessages_(ServerAppIo_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PullMessages_(ServerAppIo_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRun_(ServerAppIo_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetFab_(ServerAppIo_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PullAppInputs_(ServerAppIo_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PushAppOutputs_(ServerAppIo_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateRunStatus_(ServerAppIo_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRunStatus_(ServerAppIo_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PushLogs_(ServerAppIo_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendAppHeartbeat_(ServerAppIo_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PushObject_(ServerAppIo_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PullObject_(ServerAppIo_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ConfirmMessageReceived_(ServerAppIo_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ServerAppIo::Stub::ListAppsToLaunch(::grpc::ClientContext* context, const ::flwr::proto::ListAppsToLaunchRequest& request, ::flwr::proto::ListAppsToLaunchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::ListAppsToLaunchRequest, ::flwr::proto::ListAppsToLaunchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListAppsToLaunch_, context, request, response);
}

void ServerAppIo::Stub::async::ListAppsToLaunch(::grpc::ClientContext* context, const ::flwr::proto::ListAppsToLaunchRequest* request, ::flwr::proto::ListAppsToLaunchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::ListAppsToLaunchRequest, ::flwr::proto::ListAppsToLaunchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListAppsToLaunch_, context, request, response, std::move(f));
}

void ServerAppIo::Stub::async::ListAppsToLaunch(::grpc::ClientContext* context, const ::flwr::proto::ListAppsToLaunchRequest* request, ::flwr::proto::ListAppsToLaunchResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListAppsToLaunch_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::ListAppsToLaunchResponse>* ServerAppIo::Stub::PrepareAsyncListAppsToLaunchRaw(::grpc::ClientContext* context, const ::flwr::proto::ListAppsToLaunchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::ListAppsToLaunchResponse, ::flwr::proto::ListAppsToLaunchRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListAppsToLaunch_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::ListAppsToLaunchResponse>* ServerAppIo::Stub::AsyncListAppsToLaunchRaw(::grpc::ClientContext* context, const ::flwr::proto::ListAppsToLaunchRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListAppsToLaunchRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServerAppIo::Stub::RequestToken(::grpc::ClientContext* context, const ::flwr::proto::RequestTokenRequest& request, ::flwr::proto::RequestTokenResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::RequestTokenRequest, ::flwr::proto::RequestTokenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RequestToken_, context, request, response);
}

void ServerAppIo::Stub::async::RequestToken(::grpc::ClientContext* context, const ::flwr::proto::RequestTokenRequest* request, ::flwr::proto::RequestTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::RequestTokenRequest, ::flwr::proto::RequestTokenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestToken_, context, request, response, std::move(f));
}

void ServerAppIo::Stub::async::RequestToken(::grpc::ClientContext* context, const ::flwr::proto::RequestTokenRequest* request, ::flwr::proto::RequestTokenResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::RequestTokenResponse>* ServerAppIo::Stub::PrepareAsyncRequestTokenRaw(::grpc::ClientContext* context, const ::flwr::proto::RequestTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::RequestTokenResponse, ::flwr::proto::RequestTokenRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RequestToken_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::RequestTokenResponse>* ServerAppIo::Stub::AsyncRequestTokenRaw(::grpc::ClientContext* context, const ::flwr::proto::RequestTokenRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestTokenRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServerAppIo::Stub::GetNodes(::grpc::ClientContext* context, const ::flwr::proto::GetNodesRequest& request, ::flwr::proto::GetNodesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::GetNodesRequest, ::flwr::proto::GetNodesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetNodes_, context, request, response);
}

void ServerAppIo::Stub::async::GetNodes(::grpc::ClientContext* context, const ::flwr::proto::GetNodesRequest* request, ::flwr::proto::GetNodesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::GetNodesRequest, ::flwr::proto::GetNodesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNodes_, context, request, response, std::move(f));
}

void ServerAppIo::Stub::async::GetNodes(::grpc::ClientContext* context, const ::flwr::proto::GetNodesRequest* request, ::flwr::proto::GetNodesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNodes_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::GetNodesResponse>* ServerAppIo::Stub::PrepareAsyncGetNodesRaw(::grpc::ClientContext* context, const ::flwr::proto::GetNodesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::GetNodesResponse, ::flwr::proto::GetNodesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetNodes_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::GetNodesResponse>* ServerAppIo::Stub::AsyncGetNodesRaw(::grpc::ClientContext* context, const ::flwr::proto::GetNodesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNodesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServerAppIo::Stub::PushMessages(::grpc::ClientContext* context, const ::flwr::proto::PushAppMessagesRequest& request, ::flwr::proto::PushAppMessagesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::PushAppMessagesRequest, ::flwr::proto::PushAppMessagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushMessages_, context, request, response);
}

void ServerAppIo::Stub::async::PushMessages(::grpc::ClientContext* context, const ::flwr::proto::PushAppMessagesRequest* request, ::flwr::proto::PushAppMessagesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::PushAppMessagesRequest, ::flwr::proto::PushAppMessagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushMessages_, context, request, response, std::move(f));
}

void ServerAppIo::Stub::async::PushMessages(::grpc::ClientContext* context, const ::flwr::proto::PushAppMessagesRequest* request, ::flwr::proto::PushAppMessagesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushMessages_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PushAppMessagesResponse>* ServerAppIo::Stub::PrepareAsyncPushMessagesRaw(::grpc::ClientContext* context, const ::flwr::proto::PushAppMessagesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::PushAppMessagesResponse, ::flwr::proto::PushAppMessagesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushMessages_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PushAppMessagesResponse>* ServerAppIo::Stub::AsyncPushMessagesRaw(::grpc::ClientContext* context, const ::flwr::proto::PushAppMessagesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushMessagesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServerAppIo::Stub::PullMessages(::grpc::ClientContext* context, const ::flwr::proto::PullAppMessagesRequest& request, ::flwr::proto::PullAppMessagesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::PullAppMessagesRequest, ::flwr::proto::PullAppMessagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PullMessages_, context, request, response);
}

void ServerAppIo::Stub::async::PullMessages(::grpc::ClientContext* context, const ::flwr::proto::PullAppMessagesRequest* request, ::flwr::proto::PullAppMessagesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::PullAppMessagesRequest, ::flwr::proto::PullAppMessagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PullMessages_, context, request, response, std::move(f));
}

void ServerAppIo::Stub::async::PullMessages(::grpc::ClientContext* context, const ::flwr::proto::PullAppMessagesRequest* request, ::flwr::proto::PullAppMessagesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PullMessages_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PullAppMessagesResponse>* ServerAppIo::Stub::PrepareAsyncPullMessagesRaw(::grpc::ClientContext* context, const ::flwr::proto::PullAppMessagesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::PullAppMessagesResponse, ::flwr::proto::PullAppMessagesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PullMessages_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PullAppMessagesResponse>* ServerAppIo::Stub::AsyncPullMessagesRaw(::grpc::ClientContext* context, const ::flwr::proto::PullAppMessagesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPullMessagesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServerAppIo::Stub::GetRun(::grpc::ClientContext* context, const ::flwr::proto::GetRunRequest& request, ::flwr::proto::GetRunResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::GetRunRequest, ::flwr::proto::GetRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRun_, context, request, response);
}

void ServerAppIo::Stub::async::GetRun(::grpc::ClientContext* context, const ::flwr::proto::GetRunRequest* request, ::flwr::proto::GetRunResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::GetRunRequest, ::flwr::proto::GetRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRun_, context, request, response, std::move(f));
}

void ServerAppIo::Stub::async::GetRun(::grpc::ClientContext* context, const ::flwr::proto::GetRunRequest* request, ::flwr::proto::GetRunResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRun_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::GetRunResponse>* ServerAppIo::Stub::PrepareAsyncGetRunRaw(::grpc::ClientContext* context, const ::flwr::proto::GetRunRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::GetRunResponse, ::flwr::proto::GetRunRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRun_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::GetRunResponse>* ServerAppIo::Stub::AsyncGetRunRaw(::grpc::ClientContext* context, const ::flwr::proto::GetRunRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRunRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServerAppIo::Stub::GetFab(::grpc::ClientContext* context, const ::flwr::proto::GetFabRequest& request, ::flwr::proto::GetFabResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::GetFabRequest, ::flwr::proto::GetFabResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetFab_, context, request, response);
}

void ServerAppIo::Stub::async::GetFab(::grpc::ClientContext* context, const ::flwr::proto::GetFabRequest* request, ::flwr::proto::GetFabResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::GetFabRequest, ::flwr::proto::GetFabResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFab_, context, request, response, std::move(f));
}

void ServerAppIo::Stub::async::GetFab(::grpc::ClientContext* context, const ::flwr::proto::GetFabRequest* request, ::flwr::proto::GetFabResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFab_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::GetFabResponse>* ServerAppIo::Stub::PrepareAsyncGetFabRaw(::grpc::ClientContext* context, const ::flwr::proto::GetFabRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::GetFabResponse, ::flwr::proto::GetFabRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetFab_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::GetFabResponse>* ServerAppIo::Stub::AsyncGetFabRaw(::grpc::ClientContext* context, const ::flwr::proto::GetFabRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetFabRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServerAppIo::Stub::PullAppInputs(::grpc::ClientContext* context, const ::flwr::proto::PullAppInputsRequest& request, ::flwr::proto::PullAppInputsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::PullAppInputsRequest, ::flwr::proto::PullAppInputsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PullAppInputs_, context, request, response);
}

void ServerAppIo::Stub::async::PullAppInputs(::grpc::ClientContext* context, const ::flwr::proto::PullAppInputsRequest* request, ::flwr::proto::PullAppInputsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::PullAppInputsRequest, ::flwr::proto::PullAppInputsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PullAppInputs_, context, request, response, std::move(f));
}

void ServerAppIo::Stub::async::PullAppInputs(::grpc::ClientContext* context, const ::flwr::proto::PullAppInputsRequest* request, ::flwr::proto::PullAppInputsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PullAppInputs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PullAppInputsResponse>* ServerAppIo::Stub::PrepareAsyncPullAppInputsRaw(::grpc::ClientContext* context, const ::flwr::proto::PullAppInputsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::PullAppInputsResponse, ::flwr::proto::PullAppInputsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PullAppInputs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PullAppInputsResponse>* ServerAppIo::Stub::AsyncPullAppInputsRaw(::grpc::ClientContext* context, const ::flwr::proto::PullAppInputsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPullAppInputsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServerAppIo::Stub::PushAppOutputs(::grpc::ClientContext* context, const ::flwr::proto::PushAppOutputsRequest& request, ::flwr::proto::PushAppOutputsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::PushAppOutputsRequest, ::flwr::proto::PushAppOutputsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushAppOutputs_, context, request, response);
}

void ServerAppIo::Stub::async::PushAppOutputs(::grpc::ClientContext* context, const ::flwr::proto::PushAppOutputsRequest* request, ::flwr::proto::PushAppOutputsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::PushAppOutputsRequest, ::flwr::proto::PushAppOutputsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushAppOutputs_, context, request, response, std::move(f));
}

void ServerAppIo::Stub::async::PushAppOutputs(::grpc::ClientContext* context, const ::flwr::proto::PushAppOutputsRequest* request, ::flwr::proto::PushAppOutputsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushAppOutputs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PushAppOutputsResponse>* ServerAppIo::Stub::PrepareAsyncPushAppOutputsRaw(::grpc::ClientContext* context, const ::flwr::proto::PushAppOutputsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::PushAppOutputsResponse, ::flwr::proto::PushAppOutputsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushAppOutputs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PushAppOutputsResponse>* ServerAppIo::Stub::AsyncPushAppOutputsRaw(::grpc::ClientContext* context, const ::flwr::proto::PushAppOutputsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushAppOutputsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServerAppIo::Stub::UpdateRunStatus(::grpc::ClientContext* context, const ::flwr::proto::UpdateRunStatusRequest& request, ::flwr::proto::UpdateRunStatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::UpdateRunStatusRequest, ::flwr::proto::UpdateRunStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateRunStatus_, context, request, response);
}

void ServerAppIo::Stub::async::UpdateRunStatus(::grpc::ClientContext* context, const ::flwr::proto::UpdateRunStatusRequest* request, ::flwr::proto::UpdateRunStatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::UpdateRunStatusRequest, ::flwr::proto::UpdateRunStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateRunStatus_, context, request, response, std::move(f));
}

void ServerAppIo::Stub::async::UpdateRunStatus(::grpc::ClientContext* context, const ::flwr::proto::UpdateRunStatusRequest* request, ::flwr::proto::UpdateRunStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateRunStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::UpdateRunStatusResponse>* ServerAppIo::Stub::PrepareAsyncUpdateRunStatusRaw(::grpc::ClientContext* context, const ::flwr::proto::UpdateRunStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::UpdateRunStatusResponse, ::flwr::proto::UpdateRunStatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateRunStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::UpdateRunStatusResponse>* ServerAppIo::Stub::AsyncUpdateRunStatusRaw(::grpc::ClientContext* context, const ::flwr::proto::UpdateRunStatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateRunStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServerAppIo::Stub::GetRunStatus(::grpc::ClientContext* context, const ::flwr::proto::GetRunStatusRequest& request, ::flwr::proto::GetRunStatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::GetRunStatusRequest, ::flwr::proto::GetRunStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRunStatus_, context, request, response);
}

void ServerAppIo::Stub::async::GetRunStatus(::grpc::ClientContext* context, const ::flwr::proto::GetRunStatusRequest* request, ::flwr::proto::GetRunStatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::GetRunStatusRequest, ::flwr::proto::GetRunStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRunStatus_, context, request, response, std::move(f));
}

void ServerAppIo::Stub::async::GetRunStatus(::grpc::ClientContext* context, const ::flwr::proto::GetRunStatusRequest* request, ::flwr::proto::GetRunStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRunStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::GetRunStatusResponse>* ServerAppIo::Stub::PrepareAsyncGetRunStatusRaw(::grpc::ClientContext* context, const ::flwr::proto::GetRunStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::GetRunStatusResponse, ::flwr::proto::GetRunStatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRunStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::GetRunStatusResponse>* ServerAppIo::Stub::AsyncGetRunStatusRaw(::grpc::ClientContext* context, const ::flwr::proto::GetRunStatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRunStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServerAppIo::Stub::PushLogs(::grpc::ClientContext* context, const ::flwr::proto::PushLogsRequest& request, ::flwr::proto::PushLogsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::PushLogsRequest, ::flwr::proto::PushLogsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushLogs_, context, request, response);
}

void ServerAppIo::Stub::async::PushLogs(::grpc::ClientContext* context, const ::flwr::proto::PushLogsRequest* request, ::flwr::proto::PushLogsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::PushLogsRequest, ::flwr::proto::PushLogsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushLogs_, context, request, response, std::move(f));
}

void ServerAppIo::Stub::async::PushLogs(::grpc::ClientContext* context, const ::flwr::proto::PushLogsRequest* request, ::flwr::proto::PushLogsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushLogs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PushLogsResponse>* ServerAppIo::Stub::PrepareAsyncPushLogsRaw(::grpc::ClientContext* context, const ::flwr::proto::PushLogsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::PushLogsResponse, ::flwr::proto::PushLogsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushLogs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PushLogsResponse>* ServerAppIo::Stub::AsyncPushLogsRaw(::grpc::ClientContext* context, const ::flwr::proto::PushLogsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushLogsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServerAppIo::Stub::SendAppHeartbeat(::grpc::ClientContext* context, const ::flwr::proto::SendAppHeartbeatRequest& request, ::flwr::proto::SendAppHeartbeatResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::SendAppHeartbeatRequest, ::flwr::proto::SendAppHeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendAppHeartbeat_, context, request, response);
}

void ServerAppIo::Stub::async::SendAppHeartbeat(::grpc::ClientContext* context, const ::flwr::proto::SendAppHeartbeatRequest* request, ::flwr::proto::SendAppHeartbeatResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::SendAppHeartbeatRequest, ::flwr::proto::SendAppHeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendAppHeartbeat_, context, request, response, std::move(f));
}

void ServerAppIo::Stub::async::SendAppHeartbeat(::grpc::ClientContext* context, const ::flwr::proto::SendAppHeartbeatRequest* request, ::flwr::proto::SendAppHeartbeatResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendAppHeartbeat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::SendAppHeartbeatResponse>* ServerAppIo::Stub::PrepareAsyncSendAppHeartbeatRaw(::grpc::ClientContext* context, const ::flwr::proto::SendAppHeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::SendAppHeartbeatResponse, ::flwr::proto::SendAppHeartbeatRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendAppHeartbeat_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::SendAppHeartbeatResponse>* ServerAppIo::Stub::AsyncSendAppHeartbeatRaw(::grpc::ClientContext* context, const ::flwr::proto::SendAppHeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendAppHeartbeatRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServerAppIo::Stub::PushObject(::grpc::ClientContext* context, const ::flwr::proto::PushObjectRequest& request, ::flwr::proto::PushObjectResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::PushObjectRequest, ::flwr::proto::PushObjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushObject_, context, request, response);
}

void ServerAppIo::Stub::async::PushObject(::grpc::ClientContext* context, const ::flwr::proto::PushObjectRequest* request, ::flwr::proto::PushObjectResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::PushObjectRequest, ::flwr::proto::PushObjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushObject_, context, request, response, std::move(f));
}

void ServerAppIo::Stub::async::PushObject(::grpc::ClientContext* context, const ::flwr::proto::PushObjectRequest* request, ::flwr::proto::PushObjectResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushObject_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PushObjectResponse>* ServerAppIo::Stub::PrepareAsyncPushObjectRaw(::grpc::ClientContext* context, const ::flwr::proto::PushObjectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::PushObjectResponse, ::flwr::proto::PushObjectRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushObject_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PushObjectResponse>* ServerAppIo::Stub::AsyncPushObjectRaw(::grpc::ClientContext* context, const ::flwr::proto::PushObjectRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushObjectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServerAppIo::Stub::PullObject(::grpc::ClientContext* context, const ::flwr::proto::PullObjectRequest& request, ::flwr::proto::PullObjectResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::PullObjectRequest, ::flwr::proto::PullObjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PullObject_, context, request, response);
}

void ServerAppIo::Stub::async::PullObject(::grpc::ClientContext* context, const ::flwr::proto::PullObjectRequest* request, ::flwr::proto::PullObjectResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::PullObjectRequest, ::flwr::proto::PullObjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PullObject_, context, request, response, std::move(f));
}

void ServerAppIo::Stub::async::PullObject(::grpc::ClientContext* context, const ::flwr::proto::PullObjectRequest* request, ::flwr::proto::PullObjectResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PullObject_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PullObjectResponse>* ServerAppIo::Stub::PrepareAsyncPullObjectRaw(::grpc::ClientContext* context, const ::flwr::proto::PullObjectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::PullObjectResponse, ::flwr::proto::PullObjectRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PullObject_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::PullObjectResponse>* ServerAppIo::Stub::AsyncPullObjectRaw(::grpc::ClientContext* context, const ::flwr::proto::PullObjectRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPullObjectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ServerAppIo::Stub::ConfirmMessageReceived(::grpc::ClientContext* context, const ::flwr::proto::ConfirmMessageReceivedRequest& request, ::flwr::proto::ConfirmMessageReceivedResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flwr::proto::ConfirmMessageReceivedRequest, ::flwr::proto::ConfirmMessageReceivedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ConfirmMessageReceived_, context, request, response);
}

void ServerAppIo::Stub::async::ConfirmMessageReceived(::grpc::ClientContext* context, const ::flwr::proto::ConfirmMessageReceivedRequest* request, ::flwr::proto::ConfirmMessageReceivedResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flwr::proto::ConfirmMessageReceivedRequest, ::flwr::proto::ConfirmMessageReceivedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConfirmMessageReceived_, context, request, response, std::move(f));
}

void ServerAppIo::Stub::async::ConfirmMessageReceived(::grpc::ClientContext* context, const ::flwr::proto::ConfirmMessageReceivedRequest* request, ::flwr::proto::ConfirmMessageReceivedResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConfirmMessageReceived_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::ConfirmMessageReceivedResponse>* ServerAppIo::Stub::PrepareAsyncConfirmMessageReceivedRaw(::grpc::ClientContext* context, const ::flwr::proto::ConfirmMessageReceivedRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flwr::proto::ConfirmMessageReceivedResponse, ::flwr::proto::ConfirmMessageReceivedRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ConfirmMessageReceived_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flwr::proto::ConfirmMessageReceivedResponse>* ServerAppIo::Stub::AsyncConfirmMessageReceivedRaw(::grpc::ClientContext* context, const ::flwr::proto::ConfirmMessageReceivedRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConfirmMessageReceivedRaw(context, request, cq);
  result->StartCall();
  return result;
}

ServerAppIo::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerAppIo_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerAppIo::Service, ::flwr::proto::ListAppsToLaunchRequest, ::flwr::proto::ListAppsToLaunchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::ListAppsToLaunchRequest* req,
             ::flwr::proto::ListAppsToLaunchResponse* resp) {
               return service->ListAppsToLaunch(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerAppIo_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerAppIo::Service, ::flwr::proto::RequestTokenRequest, ::flwr::proto::RequestTokenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::RequestTokenRequest* req,
             ::flwr::proto::RequestTokenResponse* resp) {
               return service->RequestToken(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerAppIo_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerAppIo::Service, ::flwr::proto::GetNodesRequest, ::flwr::proto::GetNodesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::GetNodesRequest* req,
             ::flwr::proto::GetNodesResponse* resp) {
               return service->GetNodes(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerAppIo_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerAppIo::Service, ::flwr::proto::PushAppMessagesRequest, ::flwr::proto::PushAppMessagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::PushAppMessagesRequest* req,
             ::flwr::proto::PushAppMessagesResponse* resp) {
               return service->PushMessages(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerAppIo_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerAppIo::Service, ::flwr::proto::PullAppMessagesRequest, ::flwr::proto::PullAppMessagesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::PullAppMessagesRequest* req,
             ::flwr::proto::PullAppMessagesResponse* resp) {
               return service->PullMessages(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerAppIo_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerAppIo::Service, ::flwr::proto::GetRunRequest, ::flwr::proto::GetRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::GetRunRequest* req,
             ::flwr::proto::GetRunResponse* resp) {
               return service->GetRun(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerAppIo_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerAppIo::Service, ::flwr::proto::GetFabRequest, ::flwr::proto::GetFabResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::GetFabRequest* req,
             ::flwr::proto::GetFabResponse* resp) {
               return service->GetFab(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerAppIo_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerAppIo::Service, ::flwr::proto::PullAppInputsRequest, ::flwr::proto::PullAppInputsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::PullAppInputsRequest* req,
             ::flwr::proto::PullAppInputsResponse* resp) {
               return service->PullAppInputs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerAppIo_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerAppIo::Service, ::flwr::proto::PushAppOutputsRequest, ::flwr::proto::PushAppOutputsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::PushAppOutputsRequest* req,
             ::flwr::proto::PushAppOutputsResponse* resp) {
               return service->PushAppOutputs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerAppIo_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerAppIo::Service, ::flwr::proto::UpdateRunStatusRequest, ::flwr::proto::UpdateRunStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::UpdateRunStatusRequest* req,
             ::flwr::proto::UpdateRunStatusResponse* resp) {
               return service->UpdateRunStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerAppIo_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerAppIo::Service, ::flwr::proto::GetRunStatusRequest, ::flwr::proto::GetRunStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::GetRunStatusRequest* req,
             ::flwr::proto::GetRunStatusResponse* resp) {
               return service->GetRunStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerAppIo_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerAppIo::Service, ::flwr::proto::PushLogsRequest, ::flwr::proto::PushLogsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::PushLogsRequest* req,
             ::flwr::proto::PushLogsResponse* resp) {
               return service->PushLogs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerAppIo_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerAppIo::Service, ::flwr::proto::SendAppHeartbeatRequest, ::flwr::proto::SendAppHeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::SendAppHeartbeatRequest* req,
             ::flwr::proto::SendAppHeartbeatResponse* resp) {
               return service->SendAppHeartbeat(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerAppIo_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerAppIo::Service, ::flwr::proto::PushObjectRequest, ::flwr::proto::PushObjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::PushObjectRequest* req,
             ::flwr::proto::PushObjectResponse* resp) {
               return service->PushObject(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerAppIo_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerAppIo::Service, ::flwr::proto::PullObjectRequest, ::flwr::proto::PullObjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::PullObjectRequest* req,
             ::flwr::proto::PullObjectResponse* resp) {
               return service->PullObject(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerAppIo_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ServerAppIo::Service, ::flwr::proto::ConfirmMessageReceivedRequest, ::flwr::proto::ConfirmMessageReceivedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ServerAppIo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flwr::proto::ConfirmMessageReceivedRequest* req,
             ::flwr::proto::ConfirmMessageReceivedResponse* resp) {
               return service->ConfirmMessageReceived(ctx, req, resp);
             }, this)));
}

ServerAppIo::Service::~Service() {
}

::grpc::Status ServerAppIo::Service::ListAppsToLaunch(::grpc::ServerContext* context, const ::flwr::proto::ListAppsToLaunchRequest* request, ::flwr::proto::ListAppsToLaunchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServerAppIo::Service::RequestToken(::grpc::ServerContext* context, const ::flwr::proto::RequestTokenRequest* request, ::flwr::proto::RequestTokenResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServerAppIo::Service::GetNodes(::grpc::ServerContext* context, const ::flwr::proto::GetNodesRequest* request, ::flwr::proto::GetNodesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServerAppIo::Service::PushMessages(::grpc::ServerContext* context, const ::flwr::proto::PushAppMessagesRequest* request, ::flwr::proto::PushAppMessagesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServerAppIo::Service::PullMessages(::grpc::ServerContext* context, const ::flwr::proto::PullAppMessagesRequest* request, ::flwr::proto::PullAppMessagesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServerAppIo::Service::GetRun(::grpc::ServerContext* context, const ::flwr::proto::GetRunRequest* request, ::flwr::proto::GetRunResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServerAppIo::Service::GetFab(::grpc::ServerContext* context, const ::flwr::proto::GetFabRequest* request, ::flwr::proto::GetFabResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServerAppIo::Service::PullAppInputs(::grpc::ServerContext* context, const ::flwr::proto::PullAppInputsRequest* request, ::flwr::proto::PullAppInputsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServerAppIo::Service::PushAppOutputs(::grpc::ServerContext* context, const ::flwr::proto::PushAppOutputsRequest* request, ::flwr::proto::PushAppOutputsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServerAppIo::Service::UpdateRunStatus(::grpc::ServerContext* context, const ::flwr::proto::UpdateRunStatusRequest* request, ::flwr::proto::UpdateRunStatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServerAppIo::Service::GetRunStatus(::grpc::ServerContext* context, const ::flwr::proto::GetRunStatusRequest* request, ::flwr::proto::GetRunStatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServerAppIo::Service::PushLogs(::grpc::ServerContext* context, const ::flwr::proto::PushLogsRequest* request, ::flwr::proto::PushLogsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServerAppIo::Service::SendAppHeartbeat(::grpc::ServerContext* context, const ::flwr::proto::SendAppHeartbeatRequest* request, ::flwr::proto::SendAppHeartbeatResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServerAppIo::Service::PushObject(::grpc::ServerContext* context, const ::flwr::proto::PushObjectRequest* request, ::flwr::proto::PushObjectResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServerAppIo::Service::PullObject(::grpc::ServerContext* context, const ::flwr::proto::PullObjectRequest* request, ::flwr::proto::PullObjectResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ServerAppIo::Service::ConfirmMessageReceived(::grpc::ServerContext* context, const ::flwr::proto::ConfirmMessageReceivedRequest* request, ::flwr::proto::ConfirmMessageReceivedResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace flwr
}  // namespace proto

